### ISSUE TITLE
sam local start-api --env-vars Global settings

### ISSUE THREAD

**Issue by gakinson** [awslabs/aws-sam-cli#1496] opened 2019-11-01 00:38 UTC
### Describe your idea/feature/enhancement
I wish SAM CLI would allow me to set environment variables across all lambda functions in a repository instead of having to copy the environment variables for each lambda function.

### Proposal
Have a global section in your env-vars file that is read if there is no definition for the specific lambda function.

`
{
"GLOBAL": {
    "Stage": "Beta",
    "TABLE_NAME": "default-tablename"
  },
  "Lambda_1": {
    "Stage": "Prod",
    "TABLE_NAME": "my-table"
  }
}
`

Things to consider:
- Will need to update documentation for this

**Comment by jfuss** [comment] 2019-11-01 13:49
Duplicate of #1045

Closing

**Closed by jfuss** 2019-11-01 13:49 UTC
