### ISSUE TITLE
Special characters in environment variables are not escaped

### ISSUE THREAD

**Issue by arunvelsriram** [awslabs/aws-sam-cli#319] opened 2018-03-03 03:24 UTC
Hi,

Here is my `template.yaml`:

```
...
Runtime: go1.x
  Tracing: Active
   Environment:
     Variables:
       HANGOUTS_WEBHOOK_URL: "https://api.test.com/v1/contacts/AAAAlmeAGQ0/messages?key=hello-world"
...
```

It contains an environment variable with `=` in its value. I used `os.Getenv()` in my lambda function to read the environment variable.

When invoked locally with `sam`, `=` is not escaped the valued read is `https://chat.googleapis.com/v1/spaces/AAAAlmeAGQ0/messages?key`. 

When I run the generated binary directly `os.Getenv()` seem to read the value correctly as `https://api.test.com/v1/contacts/AAAAlmeAGQ0/messages?key=hello-world`.

This issue is mentioned in a comment [here](https://github.com/awslabs/aws-sam-local/issues/137#issuecomment-360533223).

Looks like a bug in `sam` though am not sure. If this is a bug let me know I will try to fix and raise a PR.

**Comment by jfuss** [comment] 2018-07-02 13:57
This looks like a duplicate of #303, which was resolved with the release of v0.3.0.

Closing

**Closed by jfuss** 2018-07-02 13:57 UTC
Labels: type/duplicate
