### ISSUE TITLE
Golang hot reloading support missing - should be mentioned on the output console

### ISSUE THREAD

**Issue by anujdeshpande** [awslabs/aws-sam-cli#1000] opened 2019-02-12 07:27 UTC
### Description

Sam CLI says that changes to code are reflected automatically (hot reloading). This is not true in the case of golang

### Steps to reproduce

Run any golang function and make changes to it.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS X
2. `sam --version`: SAM CLI, version 0.11.0

`Add --debug flag to command you are running`

**Comment by jfuss** [comment] 2019-02-12 18:04
Duplicate of #353, you can find suggestions from others on workarounds.

TLDR: The 'hot reloading' refers to the code or binary put in the `CodeUri`/`Code` directory will be mounted during invoke. This means if you update the binary the new binary will be picked up. Hot reloading does not mean SAM CLI will rebuild the application.

**Closed by jfuss** 2019-02-12 18:04 UTC
