### ISSUE TITLE
Allow Local Invoke of Lambdas in sub Applications

### ISSUE THREAD

**Issue by rupe120** [awslabs/aws-sam-cli#1923] opened 2020-04-16 15:52 UTC
### Describe your idea/feature/enhancement

For large applications, it is sometimes beneficial to break the template up into multiple applications. Those applications may still require a common base template for shared layers. 

I would like to be able to do the following in a base template:
- Define an application reference (`AWS::Serverless::Application`) which references a separate local template
- Call `sam local invoke <application resource name>.<lambda name> ...`

### Proposal

I believe this could be added by pulling out the list of application template refrences in the `invoke_context.py` similar to the way the functions are pulled.

A list of `InvokeContext` instances would then be created for each application template found. Passing in all of the current values and swapping out the `template_file` value

The `sam local invoke` command could then be expanded to allow for `<application resource name>.<lambda name>` or even multiple applications deep

**Comment by awood45** [comment] 2020-07-24 20:10
Closing as duplicate of #1271

**Closed by awood45** 2020-07-24 20:10 UTC
Labels: type/feature
