### ISSUE TITLE
Version 0.43 of sam does deploy the lambda(don't create a cloudformation stack)

### ISSUE THREAD

**Issue by Aleksandr-Filichkin** [awslabs/aws-sam-cli#1821] opened 2020-02-25 12:45 UTC
Looks like 0.43 version doesn't work properly. 
Command 

> sam deploy --template-file sam_output.yaml --stack-name SOME-STACK

doesn't do anything, just hung.

Downgrade to 0.41 version resolves the problem.

OS: AWS Codebuild

**Comment by jacktuck** [comment] 2020-02-26 15:26
Same here, 0.41.0 also is the latest working version for us. Interestingly 0.43.0 works locally. Did required python version change between 0.41.0 and 0.43.0?

**Comment by sriram-mv** [comment] 2020-02-26 17:54
I was not able to reproduce this in codebuild or locally on 0.43.0. How exactly does it hang? could you provide more info?

**Comment by Aleksandr-Filichkin** [comment] 2020-02-27 11:48
Hi @sriram-mv 
`version: 0.2

environment_variables:
  plaintext:
    "INPUT_FILE": "sam.yml"
    "OUTPUT_FILE": "sam_output.yaml"
    "S3_BUCKET": "some-s3"
    "STACK_NAME": "some-stackname"
    "REGION_SHORT": "use1"
    "RESOURCE_OWNER": "some email"

phases:
  pre_build:
    commands:
      - echo "Pre-Build Phase started -  SAM Deployment in ${ENVIRONMENT}"
      - ls -ltr
      - apt-get update > /dev/null
      - apt-get install jq -y > /dev/null
      - jq --version
      - wget -q https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
      - chmod +x jq-linux64
      - mv jq-linux64 $(which jq)
      - jq --version
       - pip install aws-sam-cli
#      - pip install aws-sam-cli==0.41.0 working solution!!!!!!!!
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - sam --version
      - aws --version
  build:
    commands:
      - echo -n "Build phase started for EmailDispatcher SAM in ${ENVIRONMENT}"
      - echo -n "Packaging AWS SAM"
      - echo "${INPUT_FILE} ${S3_BUCKET}"
      - sam package --template-file ${INPUT_FILE} --s3-bucket ${S3_BUCKET} --s3-prefix ${PRODUCT_NAME}/use1/packages --output-template-file ${OUTPUT_FILE}
      - PARAMETERS=$(cat config/${ENVIRONMENT}.json | jq -M -j '.[] | "\"\(.ParameterKey)=\(.ParameterValue)\" "')
      - echo -n "${PARAMETERS}"

  post_build:
    commands:
      - echo -n "Post-Build Phase running for  SAM in ${ENVIRONMENT}"
      - echo -n "${CODEBUILD_BUILD_ID}"
      - echo "Deploying Lambda Function"
      - |-
        DEPLOY_CMD="sam deploy \
        --template-file ${OUTPUT_FILE} \
        --stack-name ${STACK_NAME}-${ENVIRONMENT}-${REGION_SHORT} \
        --parameter-overrides ${PARAMETERS} \
        --capabilities CAPABILITY_NAMED_IAM \

      - echo "${DEPLOY_CMD}"
      - eval $DEPLOY_CMD
![image](https://user-images.githubusercontent.com/10498901/75442192-faab6580-596f-11ea-90fe-bd0df6053fd6.png)
`

but expected result
![image](https://user-images.githubusercontent.com/10498901/75442312-4231f180-5970-11ea-8036-de3cfe18bdcd.png)

**Comment by Aleksandr-Filichkin** [comment] 2020-02-27 11:50
[buildspec_yml.txt](https://github.com/awslabs/aws-sam-cli/files/4261439/buildspec_yml.txt)

**Comment by jacktuck** [comment] 2020-03-09 22:18
@Aleksandr-Filichkin Will it still hang if you remove `parameter-overrides`? I suspect this is linked to #1845

**Comment by sriram-mv** [comment] 2020-03-16 20:56
Closing this in favor of capturing in #1845

**Closed by sriram-mv** 2020-03-16 20:56 UTC
Labels: area/deploy, stage/needs-investigation
