### ISSUE TITLE
property Domain not defined for resource of type AWS::Serverless::Api

### ISSUE THREAD

**Issue by voathnak** [awslabs/aws-sam-cli#1738] opened 2020-01-20 20:03 UTC
Hello
I tried to use domain in AWS::Serverless::Api, I can deploy successfully but i when validating the template I got an error

`Error: [InvalidResourceException('RestApi', 'property Domain not defined for resource of type AWS::Serverless::Api')]`

**Comment by timoschilling** [comment] 2020-01-20 20:24
Duplicate of #1723

**Comment by voathnak** [comment] 2020-01-21 03:04
ahh, thank you @timoschilling

**Comment by sriram-mv** [comment] 2020-01-24 00:34
Closing as its a duplicate.

**Closed by sriram-mv** 2020-01-24 00:34 UTC
