### ISSUE TITLE
Invoking a lamnda from a lambda fails in SAM local

### ISSUE THREAD

**Issue by aleybovich** [awslabs/aws-sam-cli#207] opened 2017-11-30 18:15 UTC
I have two lambdas runnignin SAM local, one of them (lambda1) is an api endpoint and it works fine. Now, I add another lambda (lambda2) and I want lambda1 to call it, so I add this code in lambda1:

```
const lambda = new aws.Lambda({ region: 'us-east-1' });
    lambda.invoke({
        FunctionName: 'lambda2',
        InvocationType: 'Event',
        LogType: 'None',
    }, (err, data) => {
        console.log(err); // ERR HAS AN ERROR
        cb(null, { statusCode: 200, body: data });
    });
```

And Lambda2 is this:
```
module.exports.handler = (event, context, cb) => {
    cb(null, true);
};
```

I get an error in the callback:

```
{"message":"connect ECONNREFUSED 192.168.65.1:8000","code":"NetworkingError","errno":"ECONNREFUSED","syscall":"connect","address":"192.168.65.1","port":8000,"region":"us-east-1","hostname":"docker.for.mac.localhost","retryable":true,"time":"2017-11-30T18:04:24.985Z"}
```

Any ideas?

**Comment by iph** [comment] 2017-12-02 02:44
Today, I don't believe we support the exact api as Lambda itself. This sucks because of these types of oddities when you want a completely local experience.

Seems to be related to #12 

I think this would be awesome to have, might start trying to chop away at that bit if no one else is working on it.

**Comment by MarkWilliams76** [comment] 2018-02-13 12:25
Hi,

I need to call a Lambda from a Lambda too within SAM local (and then use SAM local to create my Lambdas in the console).  Has this been implemented yet?

**Comment by sebastian-schlecht** [comment] 2018-02-15 16:56
Any progress on this?

**Comment by MarkWilliams76** [comment] 2018-02-21 09:32
I set up a Lambda to Lambda call on my AWS console and the steps I followed are below.  This might be useful for setting up a corresponding call in SAM Local (as I would like to use the template file to deploy to AWS too).

1. The calling and called Lambda had to be in the same region
2. I had to create an IAM Role and attach the following policies, AWSLambdaExecute, AWSLambdaRole, and AWSLambdaBasicExecuteRole (I haven't verified if this last policy is required - see the Stackoverflow link I followed below).  Then I assigned this as the execution role for the calling Lambda. 
3. The invocation type I used was RequestResponse.  The example above used Event which didn't work for me.

https://stackoverflow.com/questions/35754766/nodejs-invoke-an-aws-lambda-function-from-within-another-lambda-function

**Comment by aleybovich** [comment] 2018-03-19 23:34
@MarkWilliams76 do both lambdas run in SAM local? The SO link you provided is about invoking a lambda from another lambda in AWS, not locally.

**Comment by MarkWilliams76** [comment] 2018-03-20 08:19
@aleybovich No. The steps I'm talking about are via AWS Console.  I posted as it's what I want to replicate locally in SAM local.

**Comment by sanathkr** [comment] 2018-06-01 00:04
Closing this issue as a dupe of #12

**Closed by sanathkr** 2018-06-01 00:04 UTC

**Comment by leandroz** [comment] 2018-09-25 13:11
@sanathkr I don't think is a duplicate, in #12 is talking about invoking the lambda function from the CLI, while here is talking about the invocation from the code itself.
I get the same ECONNREFUSED when trying to make a request to a lambda from a lambda, any ideas?

**Comment by markwaddle** [comment] 2019-01-22 00:12
this might be superseded by #510
