### ISSUE TITLE
Requests are slow

### ISSUE THREAD

**Issue by sprt** [awslabs/aws-sam-cli#362] opened 2018-04-16 19:26 UTC
Our team is using SAM Local to test our API locally and requests consistently take around 1 second to execute. It's a major bottleneck for us; the test suite takes about 12 minutes to run and most of that is due to SAM Local, unfortunately.

From what I gather from [this issue](https://github.com/awslabs/aws-sam-local/issues/134#issuecomment-331826759), the problem is that a new container is spawned every time. Are there any plans for implementing functionality to keep the containers warm (if it's even feasible)? I'd be willing to have a look but I'd need some guidance.

**Comment by mariotacke** [comment] 2018-04-27 21:06
Running into the same thing right now. Would be great to have a flag to enable hot vs. cold behavior.

**Comment by jfuss** [comment] 2018-05-08 23:15
Duplicate of #362 Closing

**Closed by jfuss** 2018-05-08 23:15 UTC

**Comment by jfuss** [comment] 2018-05-09 03:52
@mariotacke Yes that was. Thank you for pointing that out. The actually issue is #239
