### ISSUE TITLE
SAM Validate without AWS Credentials.

### ISSUE THREAD

**Issue by supreetd21** [awslabs/aws-sam-cli#2157] opened 2020-08-07 10:45 UTC
### Describe your idea/feature/enhancement
I want to add SAM Validate into my CI to check if all the SAM files are correct.
When I checked my debug logs, I found that SAM connects to AWS to send telemetry data.
I turned it off using `export SAM_CLI_TELEMETRY=0` but AWS tries to connect to `"https://iam.amazonaws.com/"`, If `sam validate` only checks if the SAM template is correct by parsing the template file, can we have a feature where it can be done without AWS Credentials?

### Proposal
- Based on the SAM_CLI_TELEMETRY env variable
- Skip the check for AWS Credentials if the validate option has been called.

**Comment by jfuss** [comment] 2020-08-10 13:37
@supreetd21 `export SAM_CLI_TELEMETRY=0` only turns off the telemetry for SAM CLI not turning off communicating with AWS Services. 

`sam validate` requires credentials so that we can validate managed policies. Without getting the list of managed policies from IAM, we cannot validate if the ones specified in the template actually exist. Due to this, AWS Credentials is a requirement to run `sam validate`.

Closing as this is by design and required.

**Closed by jfuss** 2020-08-10 13:37 UTC
