### ISSUE TITLE
Sam guided deploy not passing correct StackName

### ISSUE THREAD

**Issue by am2jm** [awslabs/aws-sam-cli#1915] opened 2020-04-07 16:12 UTC
### Description
Guided deploy is always using the same default StackName.

[Manage_stack ](https://github.com/awslabs/aws-sam-cli/blob/2bbc26a0f629841fefcf8e9a22e304f8eabbf88e/samcli/commands/deploy/guided_context.py#L103)is only called with the region and profile, so then when the bootstrap script is called it'll always pass in the [default value](https://github.com/awslabs/aws-sam-cli/blob/7ba1b444a926a9771e86d5fd023510f6f07c0ea0/samcli/lib/bootstrap/bootstrap.py#L21) and won't actually pass through the value the user gives the guided deploy.

### Steps to reproduce

Follow hello-world SAM tutorial: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html

At the `sam deploy --guided` stage be sure to enter a unique Stack Name

### Observed result
KeyError like in this closed issue https://github.com/awslabs/aws-sam-cli/issues/1640 because it's always searching for the same stack, and doesn't try to create a new one if I pass a new StackName into it.

### Expected result
The continued output of the guided deploy like in the Hello World tutorial.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: 0.47.0

I edited the two python scripts I linked above in my local environment and was able to proceed with the guided deploy which generated the .toml file for future runs.

**Comment by c2tarun** [comment] 2020-04-08 15:10
HI @am2jm,

Thanks for reporting this issue, however I am not able to reproduce it. I followed tutorial and used a unique name `sam-app-unique-name` and got following console output:

```
CloudFormation outputs from deployed stack
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Outputs
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Key                 HelloWorldFunctionIamRole
Description         Implicit IAM Role created for Hello World function
Value               arn:aws:iam::9999999999:role/sam-app-unique-name-HelloWorldFunctionRole-1NPFX0P63S6AG

Key                 HelloWorldApi
Description         API Gateway endpoint URL for Prod stage for Hello World function
Value               https://xxxxxxxxxx.execute-api.us-east-1.amazonaws.com/Prod/hello/

Key                 HelloWorldFunction
Description         Hello World Lambda Function ARN
Value               arn:aws:lambda:us-east-1:9999999999:function:sam-app-unique-name-HelloWorldFunction-17831TTOFBYOA
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Successfully created/updated stack - sam-app-unique-name in us-east-1
```

For more context managed stack is different than your stack. Managed stack is only used to manage a S3 bucket where your lambda artifacts are uploaded. If you are still facing the issue please share following details:
1. Your samconfig.toml file.
2. Console output of `sam deploy` command (please scrub account id and other personal details).

Thanks

**Comment by sriram-mv** [comment] 2020-04-27 18:51
Closing, please re-open if you have questions.

**Closed by sriram-mv** 2020-04-27 18:51 UTC
Labels: area/deploy, stage/more-info-needed
