### ISSUE TITLE
Changes to base.txt is breaking pip install on OSX

### ISSUE THREAD

**Issue by jpbarto** [awslabs/aws-sam-cli#674] opened 2018-09-21 23:17 UTC
Recent fix for #671 is resulting in a broken install using Python 2.7 and Pip 18.0 on OSX.  

$ pip install --user -e . 
Obtaining file:///private/tmp/aws-sam/aws-sam-cli-0.6.0
    Complete output from command python setup.py egg_info:
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
coverage==4.3.4
    error in aws-sam-cli setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in python_version<"3.4" at <"3.4"

**Comment by TheSriram** [comment] 2018-09-22 00:01
do you have the latest version of pip and setuptools? I'm not able to reproduce this yet.

**Comment by TheSriram** [comment] 2018-09-25 21:02
I was able to reproduce this when I was version setuptools version 18.

I think you may have installed pip with easy_install and not have the latest version of setuptools.

I'd suggest installing pip via `get-pip.py` so that you can indepedently upgrade setuptools, wheel etc.

```
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py --user
pip install --upgrade setuptools --user
export PATH=$PATH:/Users/{Username}/Library/Python/2.7/bin
pip install --user -e .
which sam
sam --version
```

I was able to get aws-sam-cli to work with those steps, hope they are useful to you. But remember, that these are global installs and not isolated.

I would very much **recommend** going the virtualenv route, so that you dont need to deal with this in future.

**Comment by jfuss** [comment] 2018-10-09 16:14
This is a failure due to an old setuptools on the system. Upgrading your setuptools will solve this issue.

Note: The PR you linked was not the cause since it has not been released yet. We have this same config in the current released version.

Closing as it is an issue on the system/python and not directly SAM CLI.

**Closed by jfuss** 2018-10-09 16:14 UTC
