### ISSUE TITLE
sam validate does not support custom credentials file with environmental variable AWS_SHARED_CREDENTIALS_FILE

### ISSUE THREAD

**Issue by piersf** [awslabs/aws-sam-cli#1022] opened 2019-02-22 19:25 UTC
### Description

I am trying to run the `sam validate` command by using credentials stored in a custom directory and file - not the default ~/.aws/ folder.
To point AWS SAM to this custom file where the credentials are stored, I am exporting the variables `AWS_SHARED_CREDENTIALS_FILE=/path/to/creds_file` and `AWS_CONFIG_FILE=/path/to/creds_file`

Then when executing `sam validate --template /path/to/template.yaml --region REGION --profile PROFILE` it fails with the below error:

```
Traceback (most recent call last):
  File "/home/user/python-virtualenvs/aws-sam/bin/sam", line 11, in <module>
    sys.exit(cli())
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/samcli/commands/validate/validate.py", line 30, in cli
    do_cli(ctx, template)  # pragma: no cover
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/samcli/commands/validate/validate.py", line 44, in do_cli
    validator.is_valid()
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/samcli/commands/validate/lib/sam_template_validator.py", line 83, in is_valid
    parameter_values={})
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/samtranslator/translator/translator.py", line 60, in translate
    deployment_preference_collection = DeploymentPreferenceCollection()
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/samtranslator/model/preferences/deployment_preference_collection.py", line 30, in __init__
    self.codedeploy_iam_role = self._codedeploy_iam_role()
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/samtranslator/model/preferences/deployment_preference_collection.py", line 89, in _codedeploy_iam_role
    ArnGenerator.generate_aws_managed_policy_arn('service-role/AWSCodeDeployRoleForLambda')
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/samtranslator/translator/arn_generator.py", line 28, in generate_aws_managed_policy_arn
    return 'arn:{}:iam::aws:policy/{}'.format(ArnGenerator.get_partition_name(),
  File "/home/user/python-virtualenvs/aws-sam/lib/python3.6/site-packages/samtranslator/translator/arn_generator.py", line 49, in get_partition_name
    region_string = region.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

However, if I export the below variables
```
export AWS_ACCESS_KEY_ID="KEY_ID"
export AWS_SECRET_ACCESS_KEY="ACCESS_KEY"
export AWS_SESSION_TOKEN="TOKEN"
export AWS_DEFAULT_REGION="REGION"
```
then the above `validate` command works fine.

In another ticket i saw that this was fixed in 0.6.0 but it seems to still be an issue. AWS SAM supports only the default ./aws/ location where it can read credentials from.

Is there a way to tell AWS SAM to read credentials from a custom file?

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: RedHat 7
2. ` SAM CLI version 0.11.0`:

Thanks,

**Comment by jfuss** [comment] 2019-02-22 19:28
Duplicate of #442

Closing

**Closed by jfuss** 2019-02-22 19:28 UTC
