### ISSUE TITLE
sam deploy --tags doesn't deploy tag keys with colons correctly

### ISSUE THREAD

**Issue by gdietz** [awslabs/aws-sam-cli#1749] opened 2020-01-24 18:32 UTC
### Description

The `sam deploy` command cuts off all parts of a tag key until the first colon and leaves what remains as the key.

### Steps to reproduce
Run `sam deploy` with the tags parameter with a tag with a colon in it: `sam deploy --stack-name mystack --tags foo:bar=hello`

### Observed result
resulting stack gets tag with key `bar` instead of `foo:bar`.

### Expected result

resulting stack gets tag with key `foo:bar` as specified in the command.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
SAM CLI, version 0.40.0

**Comment by bradduhon** [comment] 2020-01-24 20:50
I noticed this as well, my findings below mirror @gdietz.

`sam deploy ...... --tags security:project:name=test` or `sam deploy ...... --tags "security:project:name"=test`

will result in a tag of `name = test` on all resources that accept tags.

`cloudformation deploy ...... --tags "security:project:name"=test` results in a tag of `security:project:name = test` on all resources that accept tags.

**Comment by jfuss** [comment] 2020-01-24 20:59
Duplicate of #1739 and there is already a PR open with a fix: #1727

closing

**Closed** 2020-01-24 20:59 UTC
