### ISSUE TITLE
NODE_PATH is undefined if start-api --debug-port

### ISSUE THREAD

**Issue by ruben-elumen** [awslabs/aws-sam-cli#1441] opened 2019-10-03 18:03 UTC
### Description

I'm using `nodejs10.x` runtime and Lambda layers.

When I run `sam local start-api` it works nicely but when I run the same code with `sam local start api --debug-port 5858` it cannot find my node module provided as lambda layer.

It seems that if I set the `--debug-port` then the `NODE_PATH` environment variable is undefined.

### Steps to reproduce

[sam-app.zip](https://github.com/awslabs/aws-sam-cli/files/3687380/sam-app.zip)

```
~$ sam local start-api
...
2019-10-03T17:46:14.815Z	e051f530-1787-1c00-8795-f9196e3af736	INFO	process.env.NODE_PATH:
2019-10-03T17:46:14.816Z	e051f530-1787-1c00-8795-f9196e3af736	INFO	/opt/nodejs/node10/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules
```

```
~$ sam local start-api --debug-port 5858
...
2019-10-03T17:45:58.139Z	084829a2-6f1b-1bab-346f-d00675f83200	INFO	process.env.NODE_PATH:
2019-10-03T17:45:58.139Z	084829a2-6f1b-1bab-346f-d00675f83200	INFO	undefined
2019-10-03T17:45:58.140Z	084829a2-6f1b-1bab-346f-d00675f83200	ERROR	Invoke Error ... Cannot find module 'my-my-common-lib' ...
```

### Observed result

`process.env.NODE_PATH` is undefined when running `sam local start-api --debug-port 5858`

```
~$ sam local start-api --debug-port 5858 --debug
Using SAM Template at /home/ruben/git/sam-nodejs/sam-app/template.yaml
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
local start-api command is called
No Parameters detected in the template
3 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
No Parameters detected in the template
3 resources found in the template
Found '1' API Events in Serverless function with name 'HelloWorldFunction'
Detected Inline Swagger definition
Lambda function integration not found in Swagger document at path='/hello' method='get'
Found '0' APIs in resource 'ServerlessRestApi'
Removed duplicates from '0' Explicit APIs and '1' Implicit APIs to produce '1' APIs
1 APIs found in the template
Mounting HelloWorldFunction at http://127.0.0.1:3000/hello [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
Localhost server is starting up. Multi-threading = False
2019-10-03 13:57:35  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
Constructed String representation of Event to invoke Lambda. Event: {"httpMethod": "GET", "body": null, "resource": "/hello", "requestContext": {"resourceId": "123456", "apiId": "1234567890", "resourcePath": "/hello", "httpMethod": "GET", "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef", "accountId": "123456789012", "stage": "Prod", "identity": {"apiKey": null, "userArn": null, "cognitoAuthenticationType": null, "caller": null, "userAgent": "Custom User Agent String", "user": null, "cognitoIdentityPoolId": null, "cognitoAuthenticationProvider": null, "sourceIp": "127.0.0.1", "accountId": null}, "extendedRequestId": null, "path": "/hello"}, "queryStringParameters": null, "multiValueQueryStringParameters": null, "headers": {"Host": "localhost:3000", "Connection": "keep-alive", "Cache-Control": "max-age=0", "Upgrade-Insecure-Requests": "1", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", "Accept-Encoding": "gzip, deflate, br", "Accept-Language": "en-US,en;q=0.9,es-419;q=0.8,es;q=0.7", "Cookie": "Idea-211ce694=a714fe11-bfc3-4629-b461-92dd7f3dfc40", "X-Forwarded-Proto": "http", "X-Forwarded-Port": "3000"}, "multiValueHeaders": {"Host": ["localhost:3000"], "Connection": ["keep-alive"], "Cache-Control": ["max-age=0"], "Upgrade-Insecure-Requests": ["1"], "User-Agent": ["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"], "Accept-Encoding": ["gzip, deflate, br"], "Accept-Language": ["en-US,en;q=0.9,es-419;q=0.8,es;q=0.7"], "Cookie": ["Idea-211ce694=a714fe11-bfc3-4629-b461-92dd7f3dfc40"], "X-Forwarded-Proto": ["http"], "X-Forwarded-Port": ["3000"]}, "pathParameters": null, "stageVariables": null, "path": "/hello", "isBase64Encoded": false}
Found one Lambda function with name 'HelloWorldFunction'
Invoking app.lambdaHandler (nodejs10.x)
No environment variables found for function 'HelloWorldFunction'
Environment variables overrides data is standard format
Loading AWS credentials from session with profile 'None'
2019-10-03 13:57:51 Found credentials in shared credentials file: ~/.aws/credentials
Resolving code path. Cwd=/home/ruben/git/sam-nodejs/sam-app, CodeUri=hello-world/
Resolved absolute path to code is /home/ruben/git/sam-nodejs/sam-app/hello-world
Code /home/ruben/git/sam-nodejs/sam-app/hello-world is not a zip/jar file
TempConversionDepLayer is a local Layer in the template
Resolving code path. Cwd=/home/ruben/git/sam-nodejs/sam-app, CodeUri=commons/
Building image...
Requested to skip pulling images ...

Mounting /home/ruben/git/sam-nodejs/sam-app/hello-world as /var/task:ro,delegated inside runtime container
Setting up SIGTERM interrupt handler
Debugger listening on ws://0.0.0.0:5858/36313bbd-b648-43c5-92eb-f30f9903104e
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
START RequestId: e0690edd-cf74-1497-5631-6d908f8d52e0 Version: $LATEST
2019-10-03T17:58:49.810Z	e0690edd-cf74-1497-5631-6d908f8d52e0	INFO	process.env.NODE_PATH:
2019-10-03T17:58:49.810Z	e0690edd-cf74-1497-5631-6d908f8d52e0	INFO	undefined
2019-10-03T17:58:49.811Z	e0690edd-cf74-1497-5631-6d908f8d52e0	ERROR	Invoke Error	{"errorType":"Error","errorMessage":"Cannot find module 'my-my-common-lib'","code":"MODULE_NOT_FOUND","stack":["Error: Cannot find module 'my-my-common-lib'","    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)","    at Function.Module._load (internal/modules/cjs/loader.js:562:25)","    at Module.require (internal/modules/cjs/loader.js:692:17)","    at require (internal/modules/cjs/helpers.js:25:18)","    at Runtime.exports.lambdaHandler [as handler] (/var/task/app.js:7:17)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}
END RequestId: e0690edd-cf74-1497-5631-6d908f8d52e0
REPORT RequestId: e0690edd-cf74-1497-5631-6d908f8d52e0	Init Duration: 54717.45 ms	Duration: 9.76 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 52 MB	
{
  "errorType": "Error",
  "errorMessage": "Cannot find module 'my-my-common-lib'"
}
Function returned an invalid response (must include one of: body, headers, multiValueHeaders or statusCode in the response object). Response received: 
2019-10-03 13:58:50 127.0.0.1 - - [03/Oct/2019 13:58:50] "GET /hello HTTP/1.1" 502 -
2019-10-03 13:58:50 127.0.0.1 - - [03/Oct/2019 13:58:50] "GET /favicon.ico HTTP/1.1" 403 -
```

### Expected result

`process.env.NODE_PATH` points to the right lambda layers folder when running `sam local start-api --debug-port 5858`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 16.04.3 LTS  x86-64
2. `sam --version`: 0.21.0

**Comment by jfuss** [comment] 2019-10-09 17:21
This is a duplicate of #1246. There are some deeper details within that issue [here](https://github.com/awslabs/aws-sam-cli/issues/1246#issuecomment-525783483).

Closing as a duplicate of #1246

**Closed by jfuss** 2019-10-09 17:21 UTC
