### ISSUE TITLE
aws-sam-local CodeUri from within a Docker Container

### ISSUE THREAD

**Issue by bmilesp** [awslabs/aws-sam-cli#187] opened 2017-11-01 21:01 UTC
Hello,

I have an issue With setting a zip file using the CodeUrl setting within a docker container. It will unpack the file as printed by the log.Printf function on line 269 in runtime.go: 

https://github.com/awslabs/aws-sam-local/blob/d0d6ae3245833838b78b18938ae53266ce1c963a/runtime.go

There is no error on unpacking because we do not get a "ERROR: Failed to decompress archive:" from line 272.

But it cannot find the handler file once it unpacks. I believe this has something to do with the necessary docker-compose.yaml volume set to: 

`- /var/run/docker.sock:/var/run/docker.sock `

that is applied to the parent container, and how the DecompressedCwd is mounted into the lambda container that is created in the script (see line 234):

`mount := r.Cwd
	if r.DecompressedCwd != "" {
		mount = r.DecompressedCwd
	}`

this may be the issue but i'm not sureis there is an override/volume option for the DecompressedCwd?

Thanks,
-bp

**Comment by sanathkr** [comment] 2018-05-31 23:46
Closing this as a dupe of #181. This is related to the broader problem of making SAM CLI work within a Docker container

**Closed** 2018-05-31 23:46 UTC
