### ISSUE TITLE
Bind for 0.0.0.0:80 failed: port is already allocated

### ISSUE THREAD

**Issue by neuberfran** [awslabs/aws-sam-cli#370] opened 2018-04-24 17:59 UTC
Hi,
When I tried this: https://cuprak.info/2017/10/09/debugging-aws-lambda-with-netbeans/#comments

I have this issue:
![telatalvai](https://user-images.githubusercontent.com/38701397/39204944-abbdba62-47cf-11e8-9dfc-c508852f0288.png)

I have this screens with commands to help us:
![tela51](https://user-images.githubusercontent.com/38701397/39205038-fae442a0-47cf-11e8-93ee-ededb04a381a.png)
![tela52](https://user-images.githubusercontent.com/38701397/39205045-ff673cba-47cf-11e8-8058-74319e0d79b8.png)
![tela54](https://user-images.githubusercontent.com/38701397/39205050-03afd5ca-47d0-11e8-95a1-24d21e58296a.png)
![tela55](https://user-images.githubusercontent.com/38701397/39205059-091009fe-47d0-11e8-92ed-fc98d878ff45.png)

**Comment by sanathkr** [comment] 2018-05-08 22:56
Looks like you have SAM CLI already running in this port. Kill the previous instance and restart. It should work. 

Also check `docker ps` for any running Docker containers. Kill them as well.

I am going to close this Issue because this is not a bug in SAM CLI.

**Closed by sanathkr** 2018-05-08 22:56 UTC

**Comment by neuberfran** [comment] 2018-05-10 03:54
No solved. I need run **sam local start-api**  (without -d 5858)  to see correct template in my brower (http://localhost:3000/products)...

![tela79](https://user-images.githubusercontent.com/38701397/39851240-342effdc-53ec-11e8-83e9-984086d64694.png)

with -d 5858
![tela78](https://user-images.githubusercontent.com/38701397/39851250-38f293f8-53ec-11e8-83b5-88d4e18d7769.png)
![tela80](https://user-images.githubusercontent.com/38701397/39851265-49bd6032-53ec-11e8-8f68-f8897028d49f.png)

**_### what about docker-proxy:?????_** https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/39
![tela81](https://user-images.githubusercontent.com/38701397/39851350-b876b7b2-53ec-11e8-9fb3-3420f2738dcd.png)
