### ISSUE TITLE
requestContext.stage is hardcoded to `prod`

### ISSUE THREAD

**Issue by xentek** [awslabs/aws-sam-cli#455] opened 2018-06-01 19:47 UTC
I expected the value of `StageName` from my SAM template to be used as the value of `requestContext.stage` when running the template `sam local start-api`.

If this does need to be hardcoded, maybe it should be something like `samlocal` which is likely not going to be a common stage name for most folks.

**Comment by jfuss** [comment] 2018-06-04 16:47
Duplicate of #292.

Closing

**Closed by jfuss** 2018-06-04 16:47 UTC
Labels: type/duplicate
