### ISSUE TITLE
sam logs output mangled

### ISSUE THREAD

**Issue by davidjohnmaccallum** [awslabs/aws-sam-cli#1359] opened 2019-08-22 08:34 UTC
### Description

When I use `sam logs` to view my lambda function logs from the console (OSX terminal) my log messages are mangled. Note, I don't expect them to be pretty printed, but the output below is mangled.

```
2019/08/22/[$LATEST]57ae4b1bd8bf448d8e674d8231cc1970 2019-08-22T08:08:49.231000 START RequestId: ce26f5df-b0d9-4347-882a-cd89ccfc8160 Version: $LATEST
      "body": "SiteCode=TSTSTE0001&TransactionId=7e1ea8de-c4a8-4a4e-b7d1-9d29e191bc46&TransactionReference=ABC123&Amount=100.99&Status=Complete&Optional1=&Optional2=&Optional3=&Optional4=&Optional5=&CurrencyCode=ZAR&IsTes    "body": "SiteCode=TSTSTE0001&TransactionId=7e1ea8de-c4a8-4a4e-b7d1-9d29e191bc46&TransactionReference=ABC123&Amount=100.99&Status=Complete&Optional1=&Optional2=&Optional3=&Optional4=&Optional5=&CurrencyCode=ZAR&IsTest=} } "awsRequestId": "ce26f5df-b0d9-4347-882a-cd89ccfc8160"090357:function:centbee-ozow-api-OzowCallback",a5af86f6fec0b2c15e5df12f5f4b98084bcb5b621032e88a08b962d3a98ac226f84f9b748e"
} } "Hash": "28f7ebe65d84d2737cada8bbe31bc314430d00fd0d4ca726efd523a5af86f6fec0b2c15e5df12f5f4b98084bcb5b621032e88a08b962d3a98ac226f84f9b748e"fc8160    DEBUG   {
   '28f7ebe65d84d2737cada8bbe31bc314430d00fd0d4ca726efd523a5af86f6fec0b2c15e5df12f5f4b98084bcb5b621032e88a08b962d3a98ac226f84f9b748e' }-cd89ccfc8160    ERROR   { message: 'Ozow callback hash check failed',
2019/08/22/[$LATEST]57ae4b1bd8bf448d8e674d8231cc1970 2019-08-22T08:08:49.943000 2019-08-22T08:08:49.943Z        ce26f5df-b0d9-4347-882a-cd89ccfc8160    ERROR   Hash check failed
2019/08/22/[$LATEST]57ae4b1bd8bf448d8e674d8231cc1970 2019-08-22T08:08:49.983000 END RequestId: ce26f5df-b0d9-4347-882a-cd89ccfc8160
2019/08/22/[$LATEST]57ae4b1bd8bf448d8e674d8231cc1970 2019-08-22T08:08:49.983000 REPORT RequestId: ce26f5df-b0d9-4347-882a-cd89ccfc8160  Duration: 751.81 ms     Billed Duration: 800 ms         Memory Size: 128 MB     Max Memory Used: 96 MB
```

Here is the view from CloudWatch Management Console:

![Screenshot 2019-08-22 at 10 25 06](https://user-images.githubusercontent.com/2125189/63499065-63002280-c4c7-11e9-9f82-80f5305d105a.png)
![Screenshot 2019-08-22 at 10 25 12](https://user-images.githubusercontent.com/2125189/63499069-64c9e600-c4c7-11e9-9c42-ca5a6f108bb3.png)

### Steps to reproduce

I am producing these log messages like this (Node 10.x):

`console.debug(JSON.stringify({ ozowResponse }, null, 2));`

### Observed result

See description above.

### Expected result

I printed four log messages. Two console.debugs and two console.errors. I expect to see these four log messages as in the `sam logs` output.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OSX
2. `sam --version`: 0.17.0

`Add --debug flag to command you are running`

**Comment by sanathkr** [comment] 2019-08-22 23:09
I have to dig into this more. But I think this is a bug where multiline logs aren't handled well.

**Comment by davidjohnmaccallum** [comment] 2019-08-26 14:57
Thanks @sanathkr, I managed to fix the problem using the [eol](https://www.npmjs.com/package/eol) library. Newlines were coming through as carriage returns (\r) which was confusing my bash shell. Converting them to new lines (\n) did the trick.

**Comment by wmonk** [comment] 2019-10-17 08:00
I've used this to make it work properly on mac:
```

**Comment by wmonk** [comment] 2019-10-17 08:01
To add to this, it is also an issue when using sam local.

**Comment by daveykane** [comment] 2019-10-17 09:03
thanks @wmonk very helpful. For some reason that didn't quite work for me but I did adapt it to the below and it seems to have sorted the issue with multiline logs (particularly logging large nested objects):

```
sam ... 2>&1 | tr "\r" "\n"
```

**Comment by wmonk** [comment] 2019-10-17 09:04
Yep sorry should have mentioned, to get `^M` you need to do `ctrl+v ctrl+m`.

**Comment by S-Cardenas** [comment] 2019-11-21 22:31
Is there a permanent fix for this yet. I'm seeing the same behavior in `SAM CLI, version 0.22.0`? It's unfortunate to have to append `2>&1 | tr "\r" "\n"` to every call to `sam invoke` when using `nodejs10.x`, especially since the node community and AWS will disable the creation and update of lambda functions running `nodejs8.10` in Februrary 2020.

**Comment by mhart** [comment] 2019-11-23 19:30
This is due to some unfortunate internal changes in the runtimes where `console.log` is overwritten by a function that transforms all newlines to `\r`. I assume this somehow makes it easier for Cloudwatch Logs, but it definitely messes with the readability and is potentially destructive (if you had a mixture of `\r` and `\n` in your output that you wanted to keep... now you can never get that back)

It's always been docker-lambda's policy to make as minimal changes as possible to the runtimes so that the docker images are as close to production as possible – and this extends to the logging.

Workarounds are just writing straight to `process.stdout` instead of `console.log`, using a logging library that does this for you, or transforming the output yourself

**Comment by mhart** [comment] 2019-11-23 22:41
Ok, you know what – after some thinking about it, I decided to fix this issue by changing docker-lambda's behaviour.

I now transform `\r` into `\n` for all the output from the runtimes UNLESS the `DOCKER_LAMBDA_NO_MODIFY_LOGS` environment variable is set and passed into the container.

So basically, your logs should look fine now. If you're outputting `\r` deliberately and you want to keep them, then set `DOCKER_LAMBDA_NO_MODIFY_LOGS=1`, otherwise they'll be transformed into `\n`

@sanathkr you can probably consider this issue closed unless you want to do something on the aws-sam-cli end

**Comment by sanathkr** [comment] 2019-12-09 18:31
@mhart Thanks for jumping on this and fixing. I will close the issue.

**Closed by sanathkr** 2019-12-09 18:31 UTC
Labels: area/logs, stage/needs-investigation, type/bug

**Comment by code-is-art** [comment] 2020-12-11 23:26
I am having this issue with version 1.13.2 using local invoke. I have not tested it with logs yet.

**Comment by code-is-art** [comment] 2020-12-14 14:16
I take it back. I just downgraded to 1.3.0 and the issue is there. Anything with JSON.stringify will get mangled using local invoke. Can only see the fist line and the last line. So anything with \n or \r will not work. For example.
`console.log('line one\rline two\rline three\nline four\nline five')`
will output
> START RequestId: ac1ef293-d504-16a9-6b21-20a04c7f98e6 Version: $LATEST
> line fiveeT14:12:51.527Z        ac1ef293-d504-16a9-6b21-20a04c7f98e6    INFO    line one
> END RequestId: ac1ef293-d504-16a9-6b21-20a04c7f98e6

**Comment by mhart** [comment] 2020-12-14 14:48
@code-is-art SAM CLI no longer uses the docker-lambda containers where this issue was originally fixed.

Might want to open an issue over at https://github.com/aws/aws-lambda-runtime-interface-emulator

**Comment by code-is-art** [comment] 2020-12-14 14:49
Thank you

**Comment by rawpixel-vincent** [comment] 2021-05-04 10:23
Hi there,
I fixed the issue for us by adding `"test": "sam local invoke ... 2>&1 | tr \"\r\" \"\n\""` in our package.json script section.

However, this issue has been opened for two years and it seems like it should be fixed, can you either give a reason not fix the issue and add a gentle note to the sam cli documentation (with that workaround), or fix it?

If not planning to fix, adding a note to the docs will save time to figure it out -- many people like me could waste a lot of time thinking they are doing something wrong.

thanks

**Comment by habdulla-Onovative** [comment] 2021-05-20 15:52
For anyone looking for workaround that works for windows PowerShell:

https://github.com/aws/aws-lambda-runtime-interface-emulator/issues/15#issuecomment-845238643

**Comment by abecks** [comment] 2021-06-13 22:28
I'm losing faith in AWS. It has been 2 years, this issue affects most of the users of this tool, and the issue is closed.

**Comment by ntalamdotcom** [comment] 2022-05-18 12:48
2022... any fix for this dumb behaviour??

**Comment by dmngu9** [comment] 2022-09-28 11:07
I try appending `2>&1 | tr \"\r\" \"\n\""` at the end. Sometimes it works , sometimes it doesnt

**Comment by tims-realityi** [comment] 2022-11-01 21:05
An hour later and I still can't read log output.

**Comment by abecks** [comment] 2022-11-01 21:07
My team is abandoning Lambda due to the atrocious support and bugginess of the SAM tool. Dealing with SAM tool issues has eaten more time than anything else I've ever seen in development.

**Comment by tims-realityi** [comment] 2022-11-01 21:12
The real solution is the friends we made along the way.

And just not using console.log

**Comment by abecks** [comment] 2022-11-01 21:14
My favorite part is how this is has been a major issue for over a year yet this issue sits here closed
