### ISSUE TITLE
StateMachine DefinitionUri doesn't accept local files

### ISSUE THREAD

**Issue by roubaeli** [awslabs/aws-sam-cli#2027] opened 2020-06-08 15:05 UTC
**Description:**

Based on the [official documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html) the description of DefinitionUri is as follows:
```
DefinitionUri
The Amazon S3 URI or local file path of the state machine definition written in Amazon States Language.

If a local file path is provided, the template must go through the workflow that includes the sam deploy or sam package command, in order for the definition to be transformed properly.

One of Definition or DefinitionUri must be provided.

Type: String | S3Location
```

An example is even included:
```
MySampleStateMachine:
  Type: AWS::Serverless::StateMachine
  Properties:
    DefinitionUri: statemachine/my_state_machine.asl.json
    Role: arn:aws:iam::123456123456:role/service-role/my-sample-role
    DefinitionSubstitutions:
      MyFunctionArn: !GetAtt MyFunction.Arn
      MyDDBTable: !Ref TransactionTable
```

However, local files do not seem to be actually supported (by brief look at the feature commits) and using it results in `Resource is invalid. 'DefinitionUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter.` error message.

Having the StateMachine definition in a separate local file (possibly JSON definition and YML template) would be most useful, unlike linking separately uploaded S3 file.

**Steps to reproduce the issue:**
1. Use `AWS::Serverless::StateMachine` resource.
2. Define a local path as it's `DefinitionUri`.

**Observed result:**
Resource is invalid. 'DefinitionUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter.

**Expected result:**
Successful deployment.

**Comment by roubaeli** [comment] 2020-06-09 09:51
@jfuss Thanks for the fast response! I don't do `sam package` explicitly I just `sam deploy`.

And I'm sorry, this issue actually seems to be because of my wrong expectations? The SAM CLI version is indeed lower (`SAM CLI, version 0.48.0`). I'm running the command from AWS CodeBuild (image `aws/codebuild/amazonlinux2-x86_64-standard:3.0`) and I just assumed that official AWS service with AWS managed image would use the latest version of AWS tool (which is obviously not the case).

Also, it might be helpful to include the required version in the docs :-)

**Comment by jfuss** [comment] 2020-06-09 20:57
I don't know the process/ how often CodeBuild updates their images, though you should just be able to update it yourself.

> this issue actually seems to be because of my wrong expectations?

For the version you are on, the result you are seeing is expected. You will need to use 0.52.0 or later. I will work with our docs team to add a version detail to that line.

Closing as there is no action for us at this time. Feel free to re-open or create a new issue if things aren't working as expected in 0.52.0.

**Closed by jfuss** 2020-06-09 20:57 UTC

**Comment by aaronlelevier** [comment] 2020-09-03 18:47
Hi, can you say how you solved this? I am stuck on the same error.

I am on version 1.0.0

**Comment by DavidCockerill** [comment] 2021-03-04 23:51
I am seeing an issue with this also. Has anyone found a fix??

Version 1.13.2 SAM CLI

Build, package and deploy are being used.

I get this error

`Model validation failed (#: extraneous key [DefinitionUri] is not permitted)`

**Comment by aaronlelevier** [comment] 2021-03-05 01:39
I don't have this error any more. And it's now an allowed key. Maybe it's something else. I'm on the same SAM version.

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html

**Comment by DavidCockerill** [comment] 2021-03-05 02:24
@jfuss Do you have any idea what could be wrong?

**Comment by DavidCockerill** [comment] 2021-03-05 02:33
`  archiveCustomerSF:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: archiveCustomerSF
      RoleArn: 'arn:aws:iam::123:role/archiveCustomerSFRole'
      DefinitionUri: lambda/archiveCustomer/stepFunction/archive-customer-stepfunction.yaml`
      
      `sam build -t template-dev.yaml`
      
      `sam package --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-123 --output-template-file packaged.yaml`
      
      `sam deploy --template-file packaged.yaml --region us-east-2`

**Comment by aaronlelevier** [comment] 2021-03-05 14:41
Ok `Type: AWS::StepFunctions::StateMachine` should be `Type: AWS::Serverless::StateMachine`. 

They are different. The first is the Cloudformation type, the second is the SAM type.

**Comment by DavidCockerill** [comment] 2021-03-05 15:53
Ugh, can't believe i missed that.

Thank you @aaronlelevier, I really appreciate your help!!

**Comment by CHuzTakesh** [comment] 2024-09-27 17:42
Just as a note, I had the same problem yesterday: 
> "Resource is invalid. 'DefinitionUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter."
When I tried to execute the changeset with sam-template.package.yaml resulting from the command `aws cloudformation package`, **but the root cause was that I was using the awscli v1 instead v2.**
