### ISSUE TITLE
"sam build" for dotnetcore on Windows fails on first run

### ISSUE THREAD

**Issue by sanathkr** [awslabs/aws-sam-cli#1101] opened 2019-04-05 21:25 UTC
### Description

Briefly describe the bug you are facing.

### Steps to reproduce
On Windows,

1. `sam init --runtime dotnetcore2.0`
2. `sam build`

### Observed result

Please provide command output with `--debug` flag set.

```
...
Created publish archive (C:\Users\Desktop\dev\myapp\src\HelloWorld\.aws-sam\build\HelloWorldFunction\HelloWorld.zip).
Lambda project successfully packaged: C:\Users\Desktop\dev\myapp\src\HelloWorld\.aws-sam\build\HelloWorldFunction\HelloWorld.zip
Build Failed
Error: DotnetCliPackageBuilder:RunPackageAction - [Errno 2] No such file or directory: '.aws-sam\\build\\HelloWorldFunction\\HelloWorld.zip'
...
```

### Expected result
Build succeeds

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. `sam --version`: 0.14.2

`Add --debug flag to command you are running`

**Comment by TheSriram** [comment] 2019-04-08 19:45
I couldn't reproduce this on windows server 2016 across powershell, cmd and git bash. I had installed aws-sam-cli from develop.

**Comment by jfuss** [comment] 2019-04-09 16:08
There are inconsistencies in Python with regards to paths on different OS's (specific to Pathlib). 

Windows:
```
>>> import pathlib
>>> str(pathlib.path("HelloWorldFunction").resolve()) # path exists
'C:\\sam-app\\HelloWorldFunction'
>>> str(pathlib.Path("build_dir").resolve()) # path does not exist
'build_dir'
```

But on Mac:
```
>>> import pathlib
>>> str(pathlib.Path("HelloWorldFunction").resolve()) # path exists
'/Users/jfuss/sam-app/HelloWorldFunction'
>>> str(pathlib.Path("build_dir").resolve()) # path does not exist
'/Users/jfuss/sam-app/build_dir'
```

You can see that when the path does not exist on Mac you still get a full path while on Windows you get a relative. We resolve the paths before doing operations and in some cases, this means the generated function directory does not yet exist (first run case). This would yield a non full path on Windows. This is a bug within [Pathlib](https://bugs.python.org/issue32434). We can get the full path if we resolve when the base directory exists (in this case `.aws-sam`), see Pathlib bug for details.

I believe if we resolve [here](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/commands/build/build_context.py#L78) after creating `.aws-sam`, things will work as expected. Going to do a quick test on a windows machine with the patch to make sure.

**Comment by TheSriram** [comment] 2019-04-18 17:23
This has been released with `0.15.0`. Closing the issue.

**Closed by TheSriram** 2019-04-18 17:23 UTC
Labels: area/build, stage/waiting-for-release, type/bug

**Comment by rakkeshbisht** [comment] 2021-02-25 06:05
Hi Sriram,

this is still not working for me with a sample hello world app and .net core 3.1

getting below error.

2021-02-25 00:56:25,973 | DotnetCliPackageBuilder:RunPackageAction failed
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\dotnet_clipackage\actions.py", line 98, in execute
    self.subprocess_dotnet.run(arguments, cwd=self.source_dir)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\dotnet_clipackage\dotnetcli.py", line 67, in run
    raise DotnetCLIExecutionError(message=err.decode(encoding).strip())
aws_lambda_builders.workflows.dotnet_clipackage.dotnetcli.DotnetCLIExecutionError: Dotnet CLI Failed: Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-lambda does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by rakkeshbisht** [comment] 2021-02-25 06:07
"""
Actions for .NET dependency resolution with CLI Package
"""

import threading
import os
import logging

from aws_lambda_builders.actions import BaseAction, Purpose, ActionFailedError
from aws_lambda_builders.workflow import BuildMode
from .utils import OSUtils
from .dotnetcli import DotnetCLIExecutionError

LOG = logging.getLogger(__name__)


class GlobalToolInstallAction(BaseAction):
    __lock = threading.Lock()
    __tools_installed = False

    """
    A Lambda Builder Action which installs the Amazon.Lambda.Tools .NET Core Global Tool
    """

    NAME = "GlobalToolInstall"
    DESCRIPTION = "Install or update the Amazon.Lambda.Tools .NET Core Global Tool."
    PURPOSE = Purpose.COMPILE_SOURCE

    def __init__(self, subprocess_dotnet):
        super(GlobalToolInstallAction, self).__init__()
        self.subprocess_dotnet = subprocess_dotnet

    def execute(self):
        # run Amazon.Lambda.Tools update in sync block in case build is triggered in parallel
        with GlobalToolInstallAction.__lock:
            LOG.debug("Entered synchronized block for updating Amazon.Lambda.Tools")

            # check if Amazon.Lambda.Tools updated recently
            if GlobalToolInstallAction.__tools_installed:
                LOG.info("Skipping to update Amazon.Lambda.Tools install/update, since it is updated recently")
                return

            try:
                LOG.debug("Installing Amazon.Lambda.Tools Global Tool")
                self.subprocess_dotnet.run(["tool", "install", "-g", "Amazon.Lambda.Tools", "--ignore-failed-sources"])
                GlobalToolInstallAction.__tools_installed = True
            except DotnetCLIExecutionError as ex:
                LOG.debug("Error installing probably due to already installed. Attempt to update to latest version.")
                try:
                    self.subprocess_dotnet.run(
                        ["tool", "update", "-g", "Amazon.Lambda.Tools", "--ignore-failed-sources"]
                    )
                    GlobalToolInstallAction.__tools_installed = True
                except DotnetCLIExecutionError as ex:
                    raise ActionFailedError(
                        "Error configuring the Amazon.Lambda.Tools .NET Core Global Tool: " + str(ex)
                    )


class RunPackageAction(BaseAction):
    """
    A Lambda Builder Action which builds the .NET Core project using the Amazon.Lambda.Tools .NET Core Global Tool
    """

    NAME = "RunPackageAction"
    DESCRIPTION = "Execute the `dotnet lambda package` command."
    PURPOSE = Purpose.COMPILE_SOURCE

    def __init__(self, source_dir, subprocess_dotnet, artifacts_dir, options, mode, os_utils=None):
        super(RunPackageAction, self).__init__()
        self.source_dir = source_dir
        self.subprocess_dotnet = subprocess_dotnet
        self.artifacts_dir = artifacts_dir
        self.options = options
        self.mode = mode
        self.os_utils = os_utils if os_utils else OSUtils()

    def execute(self):
        try:
            LOG.debug("Running `dotnet lambda package` in %s", self.source_dir)

            zipfilename = os.path.basename(os.path.normpath(self.source_dir)) + ".zip"
            zipfullpath = os.path.abspath(os.path.join(self.artifacts_dir, zipfilename))

            arguments = ["lambda", "package", "--output-package", zipfullpath]

            LOG.debug("Zip full path Running `dotnet lambda package` in %s", zipfullpath)
            if self.mode and self.mode.lower() == BuildMode.DEBUG:
                LOG.debug("Debug build requested: Setting configuration to Debug")
                arguments += ["--configuration", "Debug"]

            if self.options is not None:
                for key in self.options:
                    if str.startswith(key, "-"):
                        arguments.append(key)
                        arguments.append(self.options[key])

            self.subprocess_dotnet.run(arguments, cwd=self.source_dir)

            # The dotnet lambda package command outputs a zip file for the package. To make this compatible
            # with the workflow, unzip the zip file into the artifacts directory and then delete the zip archive.
            self.os_utils.expand_zip(zipfullpath, self.artifacts_dir)

        except DotnetCLIExecutionError as ex:
            raise ActionFailedError(str(ex))

**Comment by wyllie2** [comment] 2021-05-20 17:22
I know this is an old thread but make sure that you have dotnet-lambda in your path.
On MacOSX I used: `export PATH=$PATH:~/.dotnet/tools`
