### ISSUE TITLE
Feature: sam build only copies source code 

### ISSUE THREAD

**Issue by dpolicastro** [awslabs/aws-sam-cli#1062] opened 2019-03-14 16:05 UTC
**Description:**
I notice `sam build` cleans up all the artifacts built inside .aws-sam and builds everything again, but sometimes I just want to update the source code to run it locally, so I think it would be good if I could pass some flags to `sam build` like `--no-dependencies` or `--only-code` to force just the copy of the source code, instead of building all artifacts again.

**Observed result:**
1. Run `sam build` for the first time, it will create all build artifacts
2. Change just the code
3. Run `sam build` again and it will build everything again (Like expected)

**Expected result:**
1. Run `sam build` for the first time, it will create all build artifacts
2. Change just the code
3. Run `sam build --only-code` and it will update just the source code in all artifacts

**Comment by jfuss** [comment] 2019-03-14 16:18
@dpolicastro Thanks for reporting. Currently its is by design but we do have an open issue for this already #805, or at least I think they are the same.

**Comment by dpolicastro** [comment] 2019-03-14 17:09
Perfect! Thanks @jfuss, I think its the same issue too, the main goal of both is to speed up development tests!

**Comment by jfuss** [comment] 2019-03-15 16:10
@dpolicastro Awesome. I am going to close this one in favor of #805.

**Closed by jfuss** 2019-03-15 16:10 UTC
