### ISSUE TITLE
Parameter Override to Empty String not parsed correctly

### ISSUE THREAD

**Issue by cBiscuit87** [awslabs/aws-sam-cli#1778] opened 2020-02-10 01:51 UTC
### Description

When attempting to override a parameter value to an empty string, the parameter override isn't parsed correctly.  If I set a value other than an empty string, it all works as expected.

### Steps to reproduce

```Powershell
sam deploy ... --parameter-overrides ParameterKey=MyParameter,ParameterValue="" ParameterKey=MyOtherParameter,ParameterValue=MyOtherValue
```

### Observed result
```
        Deploying with following values
        ===============================
        Stack name                 : my-stack
        Region                     : us-east-1
        Confirm changeset          : True
        Deployment s3 bucket       : aws-sam-cli-managed-default-...
        Capabilities               : ["CAPABILITY_NAMED_IAM"]
        Parameter overrides        : {'ParameterKey': 'MyParameter,ParameterValue=', 'MyOtherParameter': 'MyOtherValue'}

...

Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': True, 'debugFlagProvided': True, 'region': 'us-east-1', 'commandName': 'sam deploy', 'duration': 19691, 'exitReason': 'ChangeEmptyError', 'exitCode': 1, 'requestId': 'b79ba5db-43f6-42b7-81a6-c0724aeb5a62', 'installationId': 'f53bbc9a-96c6-43d0-81c0-dfe254ff1415', 'sessionId': 'b40cfcb5-79f2-4e13-af5a-e45ec4aa71f7', 'executionEnvironment': 'CLI', 'pyversion': '3.6.7', 'samcliVersion': '0.40.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: No changes to deploy. Stack MyStack is up to date
```

### Expected result

```
        Deploying with following values
        ===============================
        Stack name                 : my-stack
        Region                     : us-east-1
        Confirm changeset          : True
        Deployment s3 bucket       : aws-sam-cli-managed-default-...
        Capabilities               : ["CAPABILITY_NAMED_IAM"]
        Parameter overrides        : {'MyParameter': '', 'MyOtherParameter': 'MyOtherValue'}
```

### Other permutations attempted
This results in the same as the original issue (`ParameterKey` set to `MyParameter,ParameterValue=`):
```Powershell
sam deploy ... --parameter-overrides ParameterKey=MyParameter,ParameterValue=$null ParameterKey=MyOtherParameter,ParameterValue=MyOtherValue
```

This results in `MyParameter` set to the literal `''`:
```Powershell
sam deploy ... --parameter-overrides "ParameterKey=MyParameter,ParameterValue=''" ParameterKey=MyOtherParameter,ParameterValue=MyOtherValue
```

This results in the same as the original issue (`ParameterKey` set to `MyParameter,ParameterValue=`):
```Powershell
sam deploy ... --parameter-overrides 'ParameterKey=MyParameter,ParameterValue=""' ParameterKey=MyOtherParameter,ParameterValue=MyOtherValue
```

This results in `MyParameter` set to the literal `\"\"`:
```Powershell
sam deploy ... --parameter-overrides "ParameterKey=MyParameter,ParameterValue=\"\"" ParameterKey=MyOtherParameter,ParameterValue=MyOtherValue
```

This results in the same as the original issue (`ParameterKey` set to `MyParameter,ParameterValue=`):
```Powershell
$emptyString = ""
sam deploy ... --parameter-overrides ParameterKey=MyParameter,ParameterValue=$emptyString ParameterKey=MyOtherParameter,ParameterValue=MyOtherValue
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows (Powershell)
2. `sam --version`: SAM CLI, version 0.40.0

**Comment by cBiscuit87** [comment] 2020-02-10 15:21
I'm currently working on getting a working copy of this repo and tests up and going so I can try and fix this myself.

Another pattern that almost works:

```Powershell
sam deploy ... --parameter-overrides ParameterKey=MyParameter,ParameterValue="""" ParameterKey=MyOtherParameter,ParameterValue=MyOtherValue
```
This results in the key being left off entirely (which is progress from `ParameterKey` set to `MyParameter,ParameterValue=`).

**Comment by sriram-mv** [comment] 2020-02-10 18:30
Have you tried:

```
sam deploy  --parameter-overrides="MyParameter=\" \""
```

Quoting all of parameter overrides and escaping the quotes on the space seems to work.

**Comment by sriram-mv** [comment] 2020-02-10 18:45
https://github.com/awslabs/aws-sam-cli/issues/1652 also discusses about this. 

Closing this issue.

**Closed by sriram-mv** 2020-02-10 18:45 UTC

**Comment by mlhpdx** [comment] 2023-10-28 01:19
Just ran into this.  Why was it closed if the problem is still around?
