### ISSUE TITLE
sam local not properly deserializing event body

### ISSUE THREAD

**Issue by htambekar** [awslabs/aws-sam-cli#754] opened 2018-11-07 22:18 UTC
**Description:**

When executing an http-post request on a Java SAM local API, SAM local does not appear to properly deserialize the body of the request into a POJO object.

If I define my lambda to take a APIGatewayProxyRequestEvent, however, I can see the body contains the appropriate JSON to deserialize the object. In fact, if I pass the body to a Jackson deserializer in my handler, it properly deserializes into the POJO object.

This Lambda also works properly if deployed on AWS.

**Steps to reproduce the issue:**
1. Create a Java Lambda handler that takes a POJO object for a post request
2. curl the handler with JSON data appropriate to deserialize into the POJO object 

**Observed result:**

The POJO object passed to your Lambda handler has all null fields

**Expected result:**

The POJO object passed to your Lambda should have fields with the data defined in your post request body

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Debian 8

**Output of `sam --version`**:

$ sam --version
SAM CLI, version 0.6.0

**Optional Debug logs**:

In the logs below, notice how the constructed string representation contains a body with JSON containing a value for "jobId" but the printed KeyRequest POJO object in the handler at the bottom has jobId of null.

```
$ sam local start-api --debug
2018-11-07 10:24:36 local start-api command is called
2018-11-07 10:24:36 3 resources found in the template
2018-11-07 10:24:36 Found Serverless function with name='GetKeyFunction' and CodeUri='./target/dealer.jar'
2018-11-07 10:24:36 Trying paths: ['/home/username/.docker/config.json', '/home/username/.dockercfg']
2018-11-07 10:24:36 Found file at path: /home/username/.docker/config.json
2018-11-07 10:24:36 Found 'auths' section
2018-11-07 10:24:36 Found entry (registry=u'registry.compclout.com', username=u'wit')
2018-11-07 10:24:36 Found entry (registry=u'comp-docker.repositories.comp.com', username=u'batserve')
2018-11-07 10:24:36 http://localhost:None "GET /v1.35/_ping HTTP/1.1" 200 2
2018-11-07 10:24:36 3 resources found in the template
2018-11-07 10:24:36 Successfully parsed location from AWS::Include transform: ./swagger.yaml
2018-11-07 10:24:36 Trying to download Swagger from ./swagger.yaml
2018-11-07 10:24:36 Reading Swagger document from local file at /local-ssd/username/development/gitProjects/dealer/main/./swagger.yaml
2018-11-07 10:24:36 Resolved Sub intrinsic function: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:123456789012:function:LambdaFunction/invocations
2018-11-07 10:24:36 Extracted Function ARN: arn:aws:lambda:${AWS::Region}:123456789012:function:LambdaFunction
2018-11-07 10:24:36 Found '1' APIs in resource 'ApiGatewayApi'
2018-11-07 10:24:36 Found '1' API Events in Serverless function with name 'GetKeyFunction'
2018-11-07 10:24:36 Removed duplicates from '2' Explicit APIs and '0' Implicit APIs to produce '1' APIs
2018-11-07 10:24:36 1 APIs found in the template
2018-11-07 10:24:36 Trying paths: ['/home/username/.docker/config.json', '/home/username/.dockercfg']
2018-11-07 10:24:36 Found file at path: /home/username/.docker/config.json
2018-11-07 10:24:36 Found 'auths' section
2018-11-07 10:24:36 Found entry (registry=u'registry.compclout.com', username=u'wit')
2018-11-07 10:24:36 Found entry (registry=u'comp-docker.repositories.comp.com', username=u'batserve')
2018-11-07 10:24:36 Mounting GetKeyFunction at http://127.0.0.1:3000/keys [POST]
2018-11-07 10:24:36 You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2018-11-07 10:24:36 Localhost server is starting up. Multi-threading = True
2018-11-07 10:24:36  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2018-11-07 10:24:40 Constructed String representation of Event to invoke Lambda. Event: {"body": "{\"jobId\":1234}", "httpMethod": "POST", "resource": "/keys", "queryStringParameters": null, "requestContext": {"httpMethod": "POST", "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef", "path": "/keys", "extendedRequestId": null, "resourceId": "123456", "apiId": "1234567890", "stage": "prod", "resourcePath": "/keys", "identity": {"accountId": null, "apiKey": null, "userArn": null, "cognitoAuthenticationProvider": null, "cognitoIdentityPoolId": null, "userAgent": "Custom User Agent String", "caller": null, "cognitoAuthenticationType": null, "sourceIp": "127.0.0.1", "user": null}, "accountId": "123456789012"}, "headers": {"Content-Length": "14", "X-Forwarded-Proto": "http", "X-Forwarded-Port": "3000", "Content-Type": "application/json", "Host": "localhost:3000", "Accept": "*/*", "User-Agent": "curl/7.38.0"}, "stageVariables": null, "path": "/keys", "pathParameters": null, "isBase64Encoded": false}
2018-11-07 10:24:40 Found one Lambda function with name 'GetKeyFunction'
2018-11-07 10:24:40 Invoking com.comp.ci.core.handler.GetKeyHandler::handleRequest (java8)
2018-11-07 10:24:40 Environment variables overrides data is standard format
2018-11-07 10:24:40 Loading AWS credentials from session with profile 'None'
2018-11-07 10:24:40 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2018-11-07 10:24:40 Changing event name from before-call.apigateway to before-call.api-gateway
2018-11-07 10:24:40 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2018-11-07 10:24:40 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2018-11-07 10:24:40 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2018-11-07 10:24:40 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2018-11-07 10:24:40 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2018-11-07 10:24:40 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2018-11-07 10:24:40 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2018-11-07 10:24:40 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2018-11-07 10:24:40 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2018-11-07 10:24:40 Loading variable profile from defaults.
2018-11-07 10:24:40 Loading variable config_file from defaults.
2018-11-07 10:24:40 Loading variable credentials_file from defaults.
2018-11-07 10:24:40 Loading variable data_path from defaults.
2018-11-07 10:24:40 Loading variable profile from defaults.
2018-11-07 10:24:40 Loading variable credentials_file from defaults.
2018-11-07 10:24:40 Loading variable config_file from defaults.
2018-11-07 10:24:40 Loading variable profile from defaults.
2018-11-07 10:24:40 Loading variable metadata_service_timeout from defaults.
2018-11-07 10:24:40 Loading variable profile from defaults.
2018-11-07 10:24:40 Loading variable metadata_service_num_attempts from defaults.
2018-11-07 10:24:40 Loading variable profile from defaults.
2018-11-07 10:24:40 Looking for credentials via: env
2018-11-07 10:24:40 Looking for credentials via: assume-role
2018-11-07 10:24:40 Looking for credentials via: shared-credentials-file
2018-11-07 10:24:40 Found credentials in shared credentials file: ~/.aws/credentials
2018-11-07 10:24:40 Loading variable profile from defaults.
2018-11-07 10:24:40 Loading variable profile from defaults.
2018-11-07 10:24:40 Loading variable region from config file with value 'us-east-1'.
2018-11-07 10:24:40 Loading variable profile from defaults.
2018-11-07 10:24:40 Loading variable profile from defaults.
2018-11-07 10:24:40 Loading variable region from config file with value 'us-east-1'.
2018-11-07 10:24:40 Loading variable profile from defaults.
2018-11-07 10:24:40 Loading variable profile from defaults.
2018-11-07 10:24:40 Loading variable region from config file with value 'us-east-1'.
2018-11-07 10:24:40 Resolving code path. Cwd=/local-ssd/username/development/gitProjects/dealer/main, CodeUri=./target/dealer.jar
2018-11-07 10:24:40 Resolved absolute path to code is /local-ssd/username/development/gitProjects/dealer/main/target/dealer.jar
2018-11-07 10:24:40 Decompressing /local-ssd/username/development/gitProjects/dealer/main/target/dealer.jar

2018-11-07 10:24:41 Trying paths: ['/home/username/.docker/config.json', '/home/username/.dockercfg']
2018-11-07 10:24:41 Found file at path: /home/username/.docker/config.json
2018-11-07 10:24:41 Found 'auths' section
2018-11-07 10:24:41 Found entry (registry=u'registry.compclout.com', username=u'wit')
2018-11-07 10:24:41 Found entry (registry=u'comp-docker.repositories.comp.com', username=u'batserve')
2018-11-07 10:24:41 http://localhost:None "GET /v1.35/images/lambci/lambda:java8/json HTTP/1.1" 200 None
2018-11-07 10:24:41 Looking for auth config
2018-11-07 10:24:41 Looking for auth entry for 'docker.io'
2018-11-07 10:24:41 No entry found
2018-11-07 10:24:41 No auth config found
2018-11-07 10:24:41 http://localhost:None "POST /v1.35/images/create?tag=java8&fromImage=lambci%2Flambda HTTP/1.1" 200 None

Fetching lambci/lambda:java8 Docker container image......
2018-11-07 10:24:41 Mounting /tmp/tmp3bV0Zi as /var/task:ro inside runtime container
2018-11-07 10:24:41 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 201 196
2018-11-07 10:24:41 http://localhost:None "GET /v1.35/containers/2ff4391bd85bf869e10d951025dc49191bca7f8c88a0210d83e7d00525e20c7c/json HTTP/1.1" 200 None
2018-11-07 10:24:41 http://localhost:None "GET /v1.35/containers/2ff4391bd85bf869e10d951025dc49191bca7f8c88a0210d83e7d00525e20c7c/json HTTP/1.1" 200 None
2018-11-07 10:24:41 http://localhost:None "POST /v1.35/containers/2ff4391bd85bf869e10d951025dc49191bca7f8c88a0210d83e7d00525e20c7c/start HTTP/1.1" 204 0
2018-11-07 10:24:41 Starting a timer for 15 seconds for function 'GetKeyFunction'
2018-11-07 10:24:41 http://localhost:None "GET /v1.35/containers/2ff4391bd85bf869e10d951025dc49191bca7f8c88a0210d83e7d00525e20c7c/json HTTP/1.1" 200 None
2018-11-07 10:24:41 http://localhost:None "POST /containers/2ff4391bd85bf869e10d951025dc49191bca7f8c88a0210d83e7d00525e20c7c/attach?stream=1&stdin=0&logs=1&stderr=1&stdout=1 HTTP/1.1" 101 0
Nov 07, 2018 3:24:42 PM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
START RequestId: bfc2614e-d243-4a7a-afc4-8b28cc2aa395 Version: $LATEST
2018-11-07 15:24:43 bfc2614e-d243-4a7a-afc4-8b28cc2aa395 ERROR GetKeyHandler:72 - GetKeyHandler received null request id
com.comp.ci.core.exception.BadRequestException: 400
	at com.comp.ci.core.handler.GetKeyHandler.handleRequest(GetKeyHandler.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

END RequestId: bfc2614e-d243-4a7a-afc4-8b28cc2aa395
REPORT RequestId: bfc2614e-d243-4a7a-afc4-8b28cc2aa395	Duration: 71.93 ms	Billed Duration: 100 ms	Memory Size: 512 MB	Max Memory Used: 75 MB	
2018-11-07 10:24:43 http://localhost:None "GET /v1.35/containers/2ff4391bd85bf869e10d951025dc49191bca7f8c88a0210d83e7d00525e20c7c/json HTTP/1.1" 200 None
2018-11-07 10:24:43 http://localhost:None "DELETE /v1.35/containers/2ff4391bd85bf869e10d951025dc49191bca7f8c88a0210d83e7d00525e20c7c?force=True&link=False&v=False HTTP/1.1" 204 0
################## Endpoint is : http://0.0.0.0:8000 ##################
################### request is : KeyRequest{jobId=null, callbackToken='null'} ###################
2018-11-07 10:24:43 No Content-Type given. Defaulting to 'application/json'.
2018-11-07 10:24:43 127.0.0.1 - - [07/Nov/2018 10:24:43] "POST /keys HTTP/1.1" 200 -
```

**Comment by testphreak** [comment] 2019-07-13 02:51
Hello @jfuss! I ran into this issue as well today. Seeing that it's been a few months since this was opened, curious to know when this issue will be resolved. Running the latest version `0.18.0`. 

Appreciate the help!

**Comment by abhinav-jain09** [comment] 2019-10-09 17:55
@htambekar  would it be possible to share your code for this problem?

**Comment by mndeveci** [comment] 2020-08-12 22:30
Thanks for all the comments here.

As you mentioned I tried to re-produce the issue on a simple project. I created a Java lambda from Hello World template, and change the method type to `post`. And then updated the method parameters inside lambda to `List<String>`. So my template and my function looks like this;

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  issue-754

  Sample SAM Template for issue-754

Globals:
  Function:
    Timeout: 20

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: post
```

```
public class App implements RequestHandler<String, App.MyResultClass> {

    @Override
    public MyResultClass handleRequest(final List<String> request, final Context context) {
        System.out.println(request);
        return new MyResultClass(true, request.toString());
    }

    static class MyResultClass {
        boolean ok;
        String message;

        public MyResultClass(final boolean ok, final String message)
        {
            this.ok = ok;
            this.message = message;
        }

        public boolean isOk()
        {
            return ok;
        }

        public String getMessage()
        {
            return message;
        }
    }
}
```

When I invoke this locally, and pass list of strings as body of the request, it fails saying that it can't deserialize `List<String>` with object start tag. And if I deploy this application to my account and create a simple test in Lambda console, it will succeed.

The difference between triggering local API Gateway versus the Lambda tests, local API Gateway mimicks the way to invoke lambda from actual API Gateway through [proxy integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html)

In order to work in this way, you need to define your class as follows;
```
public class App implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent>
```

and you need to implement the handler method like this;
```
public APIGatewayProxyResponseEvent handleRequest(final APIGatewayProxyRequestEvent input, final Context context)
```

Inside the `handleRequest` method, you can access actual request body by calling `input.getBody()`. The body would be `String` representation of the actual request, so you can deserialize it there in order to use it.

I am resolving this ticket, please re-open it if the issue is different.

Thanks

**Closed by mndeveci** 2020-08-12 22:30 UTC
Labels: area/docker-lambda, type/bug
