### ISSUE TITLE
Cannot install pyodbc with sam build

### ISSUE THREAD

**Issue by plantusd** [awslabs/aws-sam-cli#1617] opened 2019-11-28 14:16 UTC
### Description

Cannot install pyodbc with sam build command neigher sam build --use-container

### Steps to reproduce

sam build

### Observed result

2 resources found in the template
Found Serverless function with name='WorkflowFunction' and CodeUri='workflows/'
Building resource 'WorkflowFunction'
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r C:\Users\dplantus\PycharmProjects\statistic-service\requirements.txt --dest C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg
Full dependency closure: {certifi==2019.11.28(wheel), wheel==0.33.6(wheel), pip==19.3.1(wheel), python-gitlab==1.13.0(wheel), python-decouple==3.3(sdist), attrs==19.3.0(wheel), setuptools==42.0.1(wheel), re
quests==2.22.0(wheel), marshmallow==3.2.2(wheel), chardet==3.0.4(wheel), jmespath==0.9.4(wheel), click==7.0(wheel), idna==2.8(wheel), sqlalchemy==1.3.11(sdist), docutils==0.15.2(wheel), chalice==1.12.0(whee
l), python-dateutil==2.8.0(wheel), pyodbc==4.0.27(sdist), enum-compat==0.0.3(wheel), urllib3==1.25.7(wheel), six==1.13.0(wheel), botocore==1.13.28(wheel)}
initial compatible: {python-gitlab==1.13.0(wheel), certifi==2019.11.28(wheel), marshmallow==3.2.2(wheel), wheel==0.33.6(wheel), docutils==0.15.2(wheel), jmespath==0.9.4(wheel), click==7.0(wheel), chalice==1
.12.0(wheel), urllib3==1.25.7(wheel), python-dateutil==2.8.0(wheel), chardet==3.0.4(wheel), idna==2.8(wheel), enum-compat==0.0.3(wheel), attrs==19.3.0(wheel), pip==19.3.1(wheel), setuptools==42.0.1(wheel),
six==1.13.0(wheel), requests==2.22.0(wheel), botocore==1.13.28(wheel)}
initial incompatible: {pyodbc==4.0.27(sdist), python-decouple==3.3(sdist), sqlalchemy==1.3.11(sdist)}
Downloading missing wheels: {pyodbc==4.0.27(sdist), python-decouple==3.3(sdist), sqlalchemy==1.3.11(sdist)}
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp38 --dest C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg pyodbc==4.0.27
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp38 --dest C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg python-decouple==3.3
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp38 --dest C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg sqlalchemy==1.3.11
compatible wheels after second download pass: {python-gitlab==1.13.0(wheel), certifi==2019.11.28(wheel), marshmallow==3.2.2(wheel), docutils==0.15.2(wheel), setuptools==42.0.1(wheel), jmespath==0.9.4(wheel)
, chalice==1.12.0(wheel), wheel==0.33.6(wheel), urllib3==1.25.7(wheel), python-dateutil==2.8.0(wheel), chardet==3.0.4(wheel), pip==19.3.1(wheel), enum-compat==0.0.3(wheel), attrs==19.3.0(wheel), click==7.0(
wheel), idna==2.8(wheel), six==1.13.0(wheel), requests==2.22.0(wheel), botocore==1.13.28(wheel)}
Build missing wheels from sdists (C compiling True): {pyodbc==4.0.27(sdist), python-decouple==3.3(sdist), sqlalchemy==1.3.11(sdist)}
calling pip wheel --no-deps --wheel-dir C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg\pyodbc-4.0.27.tar.gz
calling pip wheel --no-deps --wheel-dir C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg\python-decouple-3.3.tar.gz
calling pip wheel --no-deps --wheel-dir C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg\SQLAlchemy-1.3.11.tar.gz
compatible after building wheels (no C compiling): {python-gitlab==1.13.0(wheel), certifi==2019.11.28(wheel), python-decouple==3.3(wheel), marshmallow==3.2.2(wheel), docutils==0.15.2(wheel), setuptools==42.
0.1(wheel), jmespath==0.9.4(wheel), chalice==1.12.0(wheel), wheel==0.33.6(wheel), urllib3==1.25.7(wheel), python-dateutil==2.8.0(wheel), chardet==3.0.4(wheel), pip==19.3.1(wheel), enum-compat==0.0.3(wheel),
 attrs==19.3.0(wheel), click==7.0(wheel), idna==2.8(wheel), six==1.13.0(wheel), requests==2.22.0(wheel), botocore==1.13.28(wheel)}
Build missing wheels from sdists (C compiling False): {pyodbc==4.0.27(sdist), sqlalchemy==1.3.11(sdist)}
calling pip wheel --no-deps --wheel-dir C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg\pyodbc-4.0.27.tar.gz
calling pip wheel --no-deps --wheel-dir C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg C:\Users\dplantus\AppData\Local\Temp\tmpinil60tg\SQLAlchemy-1.3.11.tar.gz
compatible after building wheels (C compiling): {python-gitlab==1.13.0(wheel), certifi==2019.11.28(wheel), python-decouple==3.3(wheel), marshmallow==3.2.2(wheel), docutils==0.15.2(wheel), setuptools==42.0.1
(wheel), jmespath==0.9.4(wheel), chalice==1.12.0(wheel), wheel==0.33.6(wheel), urllib3==1.25.7(wheel), python-dateutil==2.8.0(wheel), chardet==3.0.4(wheel), pip==19.3.1(wheel), enum-compat==0.0.3(wheel), at
trs==19.3.0(wheel), click==7.0(wheel), idna==2.8(wheel), six==1.13.0(wheel), requests==2.22.0(wheel), botocore==1.13.28(wheel)}
Final compatible: {certifi==2019.11.28(wheel), marshmallow==3.2.2(wheel), wheel==0.33.6(wheel), urllib3==1.25.7(wheel), chardet==3.0.4(wheel), jmespath==0.9.4(wheel), pip==19.3.1(wheel), click==7.0(wheel),
idna==2.8(wheel), sqlalchemy==1.3.11(wheel), python-gitlab==1.13.0(wheel), python-decouple==3.3(wheel), docutils==0.15.2(wheel), chalice==1.12.0(wheel), python-dateutil==2.8.0(wheel), enum-compat==0.0.3(whe
el), attrs==19.3.0(wheel), setuptools==42.0.1(wheel), six==1.13.0(wheel), requests==2.22.0(wheel), botocore==1.13.28(wheel)}
Final incompatible: {pyodbc==4.0.27(wheel)}
Final missing wheels: {pyodbc==4.0.27(sdist)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\actions.py", line 39, in execute
    requirements_path=self.manifest_path
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\packager.py", line 144, in build_dependencies
    requirements_path, artifacts_dir_path, scratch_dir_path)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\packager.py", line 213, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {pyodbc==4.0.27(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflow.py", line 248, in run
    action.execute()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\actions.py", line 42, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {pyodbc==4.0.27(sdist)}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 31441, 'exitReason': 'UserException', 'exitCode'
: 1, 'requestId': '64945f99-dd6e-412f-8a69-e82f4332ec89', 'installationId': '072d408a-950f-4a21-bb6b-cea85e65da65', 'sessionId': 'dac8ddf5-86b2-42ee-999b-7278598579f2', 'executionEnvironment': 'CLI', 'pyver
sion': '3.6.7', 'samcliVersion': '0.34.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {pyodbc==4.0.27(sdist)}

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
![Annotation 2019-11-28 161517](https://user-images.githubusercontent.com/44056339/69813149-49732300-11fa-11ea-898e-f2b38636da49.png)

1. OS: Windows 10
2. `sam --version`: 0.34.0

**Comment by jfuss** [comment] 2019-11-29 14:15
Please see https://github.com/awslabs/aws-sam-cli/issues/1577#issuecomment-558678818

Closing as duplicate of #1577

**Closed by jfuss** 2019-11-29 14:15 UTC
