### ISSUE TITLE
sam deploy --paramter-override for Function's Layers with Fn::Sub: fails after upgrading to version 0.48.0 fails

### ISSUE THREAD

**Issue by smurphnturf** [awslabs/aws-sam-cli#1958] opened 2020-05-01 00:49 UTC
### Description
A Functions Layers referenced by arn has a version look up through parameters that are provided via --parameter-override flag on sam deploy. After upgrading to latest version 0.48.0 the layers fail to substitute any parameters without default values into the layer arn. Thus deployment fails.

### Steps to reproduce
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  LayerVersion:
    Type: Number
    Description: The version for the layer
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code
      Handler: index.handler
      Runtime: nodejs12.x
      Layers:
        - Fn:Sub: arn:aws:lambda:us-west-2:11111111:layer:layer-name:${LayerVersion}

### Observed result
`
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics

	Deploying with following values
	===============================
	Stack name                 : my-stack-name
	Region                     : us-west-2
	Confirm changeset          : False
	Deployment s3 bucket       : my-bucket-name
	Capabilities               : ["CAPABILITY_IAM"]
	Parameter overrides        : {'LayerVersion': '115'}

Initiating deployment
=====================
File with same data is already exists at my-stack-name/9e7216aff9934ea2895cdb12b5f4aa33. Skipping upload
2 resources found in the template
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'us-west-2', 'commandName': 'sam deploy', 'duration': 1197, 'exitReason': 'InvalidLayerVersionArn', 'exitCode': 1, 'requestId': '8615248c-be1a-48ca-baf9-48e230fe2ca5', 'installationId': '129e166f-e3d7-4041-88e8-db7a07f6a5ce', 'sessionId': 'a399738e-227e-435c-a53e-fd837506bbba', 'executionEnvironment': 'CLI', 'pyversion': '3.7.7', 'samcliVersion': '0.48.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: arn:aws:lambda:us-east-1:1111111:layer:layer-name:LayerVersion is an Invalid Layer Arn.
`
### Expected result

successful deployment with layer arn: 
arn:aws:lambda:us-west-2:1111111:layer:layer-name:115

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac and Ubuntu
2. `sam --version`: 0.48.0

**Comment by brysontyrrell** [comment] 2020-05-03 20:16
I just ran into this today too. Updated SAM between usage and my stack parameter pointing to an SSM value cause "Invalid Layer Arn" errors on deployment. Downgrading to 0.47.0 allowed me to deploy again.

**Comment by smurphnturf** [comment] 2020-05-04 00:41
> I just ran into this today too. Updated SAM between usage and my stack parameter pointing to an SSM value cause "Invalid Layer Arn" errors on deployment. Downgrading to 0.47.0 allowed me to deploy again.

Yes downgrading worked for me too. @brysontyrrell May I ask how you downgraded? I didn't find any offical way of downgrading or installing a specific version for linux based machines. Im using the sam cli in some CI/CD pipelines with containers.

**Comment by brysontyrrell** [comment] 2020-05-04 01:37
@smurphnturf Use this `pip` command:
```
pip install -U aws-sam-cli==0.47.0
```

**Comment by sriram-mv** [comment] 2020-05-04 23:33
The fix is in develop and will be part of the next release.

**Comment by smurphnturf** [comment] 2020-05-05 11:54
Great news @sriram-mv! Is there a PR I can check out? Im only curious.

**Comment by sriram-mv** [comment] 2020-05-06 17:12
Yes PR has been merged into develop: https://github.com/awslabs/aws-sam-cli/pull/1961

**Comment by jfuss** [comment] 2020-05-18 13:22
Closing this was patched in https://github.com/awslabs/aws-sam-cli/releases/tag/v0.49.0

**Comment by jfuss** [comment] 2020-05-18 13:23
Closing this was patched in https://github.com/awslabs/aws-sam-cli/releases/tag/v0.49.0

**Closed by jfuss** 2020-05-18 13:23 UTC
Labels: stage/waiting-for-release

**Comment by elviraShorko** [comment] 2020-06-12 07:00
Hi @jfuss,
I'm getting the error `{{resolve:ssm:string:1}} is an Invalid Layer Arn` with sam version >= 0.48.0. It works only with version 0.47.0. 
Also, when we upload a new version of layer code, layer version is changed in the Layers (e.g. goes from `arn:aws:lambda:{region}:212454554:layer:{LayerName}:1` to `arn:aws:lambda:{region}:212454554:layer:{LayerName}:2`) and the newest value for Layer Arn is stored in the SSM Parameter. 
After that we are setting the newest version of the SSM parameter in the CF `AWS::Serverless::Function` and do `sam deploy`. After deploy if you open the Lambda function in the AWS console you will find that is using the previous version of the Layer (`arn:aws:lambda:{region}:212454554:layer:{LayerName}:1` instead `arn:aws:lambda:{region}:212454554:layer:{LayerName}:2`).
We are working with `sam --version`: 0.47.0.

**Comment by shanesiebken** [comment] 2020-07-23 15:06
This seems to be broken again in `sam --version` 1.0.0. `sam build` is still working, but deploy fails with an SSM path for a layer arn.

**Comment by aahung** [comment] 2020-11-12 18:20
> This seems to be broken again in sam --version 1.0.0. sam build is still working, but deploy fails with an SSM path for a layer arn.

I cannot reproduce this bug as in 1.9.0, @shanesiebken can you try it again to see if your issue still persists?
