### ISSUE TITLE
Sam Build Failed: NodejsNpmBuilder:NpmPack

### ISSUE THREAD

**Issue by chestongo** [awslabs/aws-sam-cli#1906] opened 2020-03-28 18:43 UTC
After trying a SAM project using python, I suddenly need to create a package.json file for each lambda function.

Otherwise, I will get an error: 
```
Build Failed
Error: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! code ENOLOCAL
```

I don't need any node_modules for my lambda function, so I would like not to include it in my folder.

For each function, this script will run.
```
Running NodejsNpmBuilder:NpmPack
Running NodejsNpmBuilder:CopyNpmrc
Running NodejsNpmBuilder:CopySource
Running NodejsNpmBuilder:NpmInstall
Running NodejsNpmBuilder:CleanUpNpmrc
```

**Comment by sriram-mv** [comment] 2020-03-30 18:54
This is interesting, could you add more detail to this? did you have a python project in a different directory and switching back to build a node project is giving you this issue?

**Comment by chestongo** [comment] 2020-03-30 20:46
I started a SAM node project with the following commands:
```
sam init
1 - AWS Quick Start Templates
1 - nodejs12.x
```
When I create my own function handlers without the package.json file. The build will still work, the commands below won't be displayed.
```
Running NodejsNpmBuilder:NpmPack
Running NodejsNpmBuilder:CopyNpmrc
Running NodejsNpmBuilder:CopySource
Running NodejsNpmBuilder:NpmInstall
Running NodejsNpmBuilder:CleanUpNpmrc
```

However later when, I started a SAM python project with the following commands:
```
sam init
1 - AWS Quick Start Templates
2 - python3.8
1 - Hello World Example
```
And remove the requirements.txt file, the commands following command and error will occur:
```
Running PythonPipBuilder:ResolveDependencies
Build Failed
Error: PythonPipBuilder:ResolveDependencies - Requirements file not found:  
```

Now, even after changing back to a SAM node project. My package.json file is required in the same path as my function. 

I am a little confused now, why is this suddenly required?

**Comment by awood45** [comment] 2020-04-01 20:20
What is the runtime in your `templates.yml` file for that function? That is what we use to determine what build expectations are.

**Comment by awood45** [comment] 2020-04-01 20:22
It may also help to know which files were present (don't need to see the contents), and what the CodeUri/Runtime were, in each case mentioned.

**Comment by chestongo** [comment] 2020-04-01 20:40
> What is the runtime in your `templates.yml` file for that function? That is what we use to determine what build expectations are.

    Runtime: nodejs12.x

**Comment by chestongo** [comment] 2020-04-01 21:01
> It may also help to know which files were present (don't need to see the contents), and what the CodeUri/Runtime were, in each case mentioned.

```
    ├── handlers
    │   ├── ackermann
    │   │   ├── index.js
    │   │   └── package.json
    │   ├── factorial
    │   │   ├── index.js
    │   │   └── package.json
    │   └── fibonacci
    │       ├── index.js
    │       └── package.json
    ├── samconfig.toml
    ├── swagger.yaml
    └── template.yaml
```

**Comment by jfuss** [comment] 2020-04-14 14:54
@chestongo 

> And remove the requirements.txt file, the commands following command and error will occur:

That is expected. Build requires the manifest (in this case requirements.txt) to be in the directory of your CodeUri.

> Now, even after changing back to a SAM node project. My package.json file is required in the same path as my function.
I am a little confused now, why is this suddenly required?

Yes, this is expected and a requirement of `sam build`. If you want your package.json elsewhere, you can pass it to `sam build` through the `--manifest` option.

Closing as the behavior described is how `sam build` was designed.

**Closed by jfuss** 2020-04-14 14:54 UTC
Labels: area/build

**Comment by chestongo** [comment] 2020-04-22 01:43
> Yes, this is expected and a requirement of sam build. If you want your package.json elsewhere, you can pass it to sam build through the --manifest option.

But for my first node project, the package.json was not required. I could deploy my lambda functions without any node_modules and package.json. When i go to my first node project folder, i could still run `sam build` without running Running the command: `NodejsNpmBuilder:NpmPack.`

I am using lambda layers for my old node project, so including a package.json in every function looks unnecessary for me.

**Comment by chestongo** [comment] 2020-04-22 01:47
My .aws-sam directory:

Before:
```
.
└── build
    └── template.yaml
```

After:
```
.
└── build
    ├── HelloWorldFunction
    │   ├── app.js
    │   └── package.json
    └── template.yaml
```

**Comment by jfuss** [comment] 2020-04-22 14:37
@chestongo By the looks of it, your first project doesn't have any functions in it. So `sam build` doesn't actually build anything. That is why when you added a function, you see this requirement surface.

If you have all your dependencies in a layer and your function code itself doesn't need to build anything, then don't use `sam build` as it doesn't provide you any value.

**Comment by chestongo** [comment] 2020-04-23 01:31
> @chestongo By the looks of it, your first project doesn't have any functions in it.

It does, but the functions doesn't go to the build folder. So i guess `sam build` will only build my template in the `.aws-sam/build` folder. After building, i can run `sam deploy` this will deploy my functions, described in my templates using ContentUri (the functions are in the same folder), directly to my s3 bucket. I don't need to include a `package.json` in my functions folder. `sam deploy` knows where my functions are, and can deploy it to my s3 bucket automatically.

I know, `sam deploy` without using `sam build` works for my second project, but not for my first project. I need to build my template first, before i can deploy my changes. I wonder why `sam build` will succeed on my first project and not on my second project. And also why `sam build` is required to run on my first project and not on my second project.

**Comment by chestongo** [comment] 2020-04-23 01:35
The differences in command line:

First project:
```
$ sam build
Build Succeeded
Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml
Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided
```

Second project:
```
$ sam build
Building resource 'HelloWorldFunction'
Running NodejsNpmBuilder:NpmPack
Build Failed
Error: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! code ENOLOCAL
npm ERR! Could not install from "<<path>>" as it does not contain a package.json file.
```

**Comment by jgomes94** [comment] 2020-11-16 15:47
@chestongo did you find a solution for this? I'm having a similar issue

**Comment by jgomes94** [comment] 2020-11-16 16:40
In my case the folder containing the lambda code did not match the codeUri in the template (one of the chars was not capsed). This caused an error on code build because it runs in a linux env where it is case sensitive, hope it helps.

**Comment by chestongo** [comment] 2020-11-16 19:17
I am currently not using python anymore, however... I remembered you had to include the requirements.txt file, even when you are not using it.

**Comment by smaruy30** [comment] 2021-01-03 16:36
@jgomes94 @chestongo  Probably using `Type: AWS::Lambda::Function` in your template? `Type: AWS::Serverless::Function` worked for me.

**Comment by Y0gyaa** [comment] 2025-04-04 06:17
I did a an npm install  before sam build and it solved this error for me
