### ISSUE TITLE
System cannot find the file specified when running "sam package" command

### ISSUE THREAD

**Issue by jltjohanlindqvist** [awslabs/aws-sam-cli#581] opened 2018-07-27 09:03 UTC
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\sam-script.py", line 11, in <module>
    load_entry_point('aws-sam-cli==0.4.0', 'console_scripts', 'sam')()
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\samcli\commands\package\__init__.py", line 22, in cli
    do_cli(args)  # pragma: no cover
  File "c:\python27\lib\site-packages\samcli\commands\package\__init__.py", line 26, in do_cli
    execute_command("package", args)
  File "c:\python27\lib\site-packages\samcli\lib\samlib\cloudformation_command.py", line 18, in execute_command
    subprocess.check_call([aws_cmd, 'cloudformation', command] + list(args))
  File "c:\python27\lib\subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

I get this error when running `sam package` with the specified flags in the `README.md` for the project that is created using `sam init --runtime go1.x`

I found that if I change the following line to set the `aws_cmd` to `aws` always instead of `aws.cmd` on windows I can run `sam package` without getting an error.

https://github.com/awslabs/aws-sam-cli/blob/48f8b1f0b6b22ccb25d2ee594a6a42d87c40584b/samcli/lib/samlib/cloudformation_command.py#L16

Used PowerShell on Windows 10.

Hope this helps.

**Comment by mjiderhamn** [comment] 2018-07-28 13:48
I'm seeing the same thing regarding `aws` vs `aws.cmd`

May be a duplicate of #415

**Comment by jfuss** [comment] 2018-08-13 13:04
@mjiderhamn Yes this looks to be a duplicate of #415. 

Closing this in favor of the older one.

**Closed by jfuss** 2018-08-13 13:04 UTC
