### ISSUE TITLE
Parameter override breaks function timeout 

### ISSUE THREAD

**Issue by mbradburn** [awslabs/aws-sam-cli#1116] opened 2019-04-11 21:51 UTC
### Description

Supplying a function timeout as parameter with override leads to python TypeError

### Steps to reproduce

1. Set template Function.Properties.Timeout to "!Ref timeoutParam", with corresponding Parameters.timeoutParam.
2. Do "sam local invoke --no-event --parameter-overrides "ParameterKey=timeoutParam,ParameterValue=60"

### Observed result

2019-04-11 14:46:15 Starting a timer for 60 seconds for function 'Function'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1164, in run
    self.finished.wait(self.interval)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 299, in wait
    if timeout > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

### Expected result

Expected normal execution

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS mojave 10.14.4
2. `sam --version`: SAM CLI, version 0.14.2

`Add --debug flag to command you are running`
[template.yaml.txt](https://github.com/awslabs/aws-sam-cli/files/3070747/template.yaml.txt)

**Comment by jfuss** [comment] 2019-04-11 22:03
Duplicate of https://github.com/awslabs/aws-sam-cli/issues/925

Closing

**Closed by jfuss** 2019-04-11 22:03 UTC
