### ISSUE TITLE
Error: PythonPipBuilder:ResolveDependencies - {pyodbc==4.0.27(sdist)}

### ISSUE THREAD

**Issue by thanuj11** [awslabs/aws-sam-cli#1577] opened 2019-11-21 23:01 UTC
Error Installing python pyodbc package in aws sam. (cmd used: sam build --use-container)

Error:
Build Failed
Error: PythonPipBuilder:ResolveDependencies - {pyodbc==4.0.27(sdist)}

Details:
Python Version: 3.6
sam version: SAM CLI, version 0.31.0
aws cli version: aws-cli/1.16.251

pip install pyodbc works, but when I include pyodbc in requirements.txt and run sam build --use-container it errors out.

Any comments or fixes to solve this issue

**Comment by TheSriram** [comment] 2019-11-25 23:01
This is interesting, when building within the container we look for manylinux wheels. can you reproduce on a normal sam build as well?

**Comment by thanuj11** [comment] 2019-11-26 15:15
I tried using sam build, but sam build also failed

command: sam build

**Build Failed
Error: PythonPipBuilder:ResolveDependencies - {pyodbc==4.0.27(wheel)}**

**Comment by jfuss** [comment] 2019-11-26 15:21
@thanuj11 `pyodbc` does not have linux wheels, so we have to build from source. I would assume this is the part that is failing (some missing dependency or something?). The path forward I can think of is to manually build it and vendor the dependency directly or place it in a layer that you can use.

**Comment by thanuj11** [comment] 2019-11-26 15:35
@jfuss, yes, It is not able to find Linux wheels for pyodbc. I will try to build manually and use it as a layer. 

Thanks.

**Comment by plantusd** [comment] 2019-12-01 15:07
I've built pyodbc and trying to attach as lambda layer, but I always get these two errors:
ImportError: libodbc.so.2: cannot open shared object file: No such file or directory
or this
AttributeError: module 'pyodbc' has no attribute 'paramstyle'
Here's he layer
[pyodbc.zip](https://github.com/awslabs/aws-sam-cli/files/3908330/pyodbc.zip)

Thanks in advance!

**Comment by sanathkr** [comment] 2019-12-09 18:21
@plantusd I am not sure what's going on. Do you need to modify LD_LIBRARY_PATH env vars to point to .so files in the layer?

**Comment by Mike-Nahmias** [comment] 2019-12-20 19:19
I was able to get pyodbc working by using alexanderluiscampino's layer [here](https://github.com/alexanderluiscampino/lambda-layers).

**Comment by danyags** [comment] 2019-12-20 22:35
> I was able to get pyodbc working by using alexanderluiscampino's layer [here](https://github.com/alexanderluiscampino/lambda-layers).

@Mike-Nahmias How did you setup your project?

**Comment by Mike-Nahmias** [comment] 2019-12-21 04:02
@danyags The pyodbc folder I linked to is in the root of my project and then I add it as a layer in my template:

```
Resources:
  pyodbcLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pyodbcLayer
      Description: Layer containing pyodbc and SQL driver, as sam build failed to compile
      ContentUri: pyodbc_layer/
      CompatibleRuntimes: [python3.7]
```

**Comment by danyags** [comment] 2019-12-23 14:39
@Mike-Nahmias I downloaded the file, pyodbc folder is in the root of my project, but I'm getting an error: No module named 'pyodbc'. 

my template.yaml file is as below

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  pyodbcLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pyodbcLayer
      Description: Layer containing pyodbc and SQL driver, as sam build failed to compile
      ContentUri: pyodbc/
      CompatibleRuntimes: [python3.7]
      
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

**Comment by Mike-Nahmias** [comment] 2019-12-23 15:37
@danyags I think you forgot to add the layer to your function. Sorry, I didn't make that clear. It should look something like this:

```
Resources:
  pyodbcLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pyodbcLayer
      Description: Layer containing pyodbc and SQL driver, as sam build failed to compile
      ContentUri: pyodbc/
      CompatibleRuntimes: [python3.7]

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Layers:
        - !Ref pyodbcLayer
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
```

**Comment by danyags** [comment] 2019-12-23 17:41
@Mike-Nahmias I got a new error...According to your message, my template.yaml file looks as below:

`Resources:
  pyodbcLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pyodbcLayer
      Description: Layer containing pyodbc and SQL driver, as sam build failed to compile
      ContentUri: pyodbc/
      CompatibleRuntimes: [python3.7]
      
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Layers:
        - !Ref pyodbcLayer      
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get`

![captureError](https://user-images.githubusercontent.com/22844203/71372142-1dd52580-2579-11ea-967e-ee81b0924378.PNG)

**Comment by Mike-Nahmias** [comment] 2019-12-23 18:04
@danyags I'm not sure, it works for me. Are you able to run the default hello-world app without the layer? The error makes me thing that would fail too. Did you run `sam build` before `sam local start-api`? Did you do the shared drive configuration when installing docker as described [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-windows.html#serverless-sam-cli-install-windows-docker)?

**Comment by danyags** [comment] 2019-12-23 18:16
@Mike-Nahmias I had the configuration of dokcer as the links says, I run the build command before to start api.
If I run the function without layer configuration the result is OK
![image](https://user-images.githubusercontent.com/22844203/71373824-1b28ff00-257e-11ea-9b94-67fb39b45185.png)

**Comment by djm** [comment] 2020-02-01 22:03
If anyone is still after an answer for this:

`pip install wheel` fixed it for me, without having to use `--use-container`.

Longer explanation: [aws-lambda-builders](https://github.com/awslabs/aws-lambda-builders/blob/24f0aca6ed41ec2b08333655adbd1433f14cdc9e/aws_lambda_builders/workflows/python_pip/packager.py#L217) which is in control of the `pip` download process looks for linux compatable wheels for each dependency. For those where it only has the `sdist` (basically raw code) it attempts to build a wheel, and for that it requires the `wheel` package. If you don't have it installed you'll get this hard to debug error.

**Comment by sriram-mv** [comment] 2020-02-10 20:16
Closing as original query has been answered.

**Closed by sriram-mv** 2020-02-10 20:16 UTC
Labels: area/build, stage/more-info-needed

**Comment by Mike-Nahmias** [comment] 2020-02-10 21:51
@djm I made sure wheel is installed and my build still fails.

**Comment by aaronlelevier** [comment] 2020-02-14 01:51
+1

**Comment by mpeckdsd** [comment] 2020-06-03 14:58
@Mike-Nahmias do you have a repo with the folder structure? im still getting import errors after copying the folder into my root directory.

**Comment by alinada101** [comment] 2021-09-16 16:09
> If anyone is still after an answer for this:
> 
> `pip install wheel` fixed it for me, without having to use `--use-container`.
> 
> Longer explanation: [aws-lambda-builders](https://github.com/awslabs/aws-lambda-builders/blob/24f0aca6ed41ec2b08333655adbd1433f14cdc9e/aws_lambda_builders/workflows/python_pip/packager.py#L217) which is in control of the `pip` download process looks for linux compatable wheels for each dependency. For those where it only has the `sdist` (basically raw code) it attempts to build a wheel, and for that it requires the `wheel` package. If you don't have it installed you'll get this hard to debug error.

It worked for me too

**Comment by ao-white** [comment] 2021-11-03 00:48
I'm having this issue. `pip install wheel` doesn't seem to work for me. I also have the pyodbc layer @Mike-Nahmias mentions as well as a the same template.yaml file. Using python 3.7. 
Also do I still put pyodbc in my requirements.txt file if I'm trying to set it as a lambda layer? I'm learning AWS sam and lambda so excuse my ignorance.
The following is what my project folder structure is (using the Hello-World sam template):
![sam_project](https://user-images.githubusercontent.com/56939248/139970582-66a9be46-6ec1-488a-8aa5-e6f841042d9f.jpg)

**Comment by jgc93** [comment] 2022-03-03 23:07
still getting the error 
"Unable to import module 'lambda-handler': libodbc.so.2: cannot open shared object file: No such file or directory"

I set my Lambda's environment variables to include env_vars["LD_LIBRARY_PATH"] = "/opt/pyodbc/:$LD_LIBRARY_PATH"
where pyodbc is the name of the folder into which I unzipped https://github.com/alexanderluiscampino/lambda-layers

Not sure what step I'm missing. Would really appreciate help!

**Comment by charlescol** [comment] 2022-03-04 04:14
For those who haven't found it yet, I have a solution that just worked for me : 
- open cmd as admin
- cd <lambda project folder>/pyodbc/python/
- mkdir pyodbc                  -> the solution was here
- pip3 install -t . pyodbc

Then create a layer by writing the code in the main .yaml file (with ContentUri: pyodbc/) and it works !
So what didn't work was that the pyodbc.cp310-win_amd64.pyd and pyodbc.pyi files which were not in a folder sub-folder named pyodbc.
