### ISSUE TITLE
java.lang.ClassNotFoundException: com.example.StreamLambdaHandler

### ISSUE THREAD

**Issue by abidk** [awslabs/aws-sam-cli#462] opened 2018-06-06 11:41 UTC
**Description:**

When executing the spring-boot example:

```
mvn archetype:generate -DgroupId=my.service -DartifactId=my-service -Dversion=1.0-SNAPSHOT \
       -DarchetypeGroupId=com.amazonaws.serverless.archetypes \
       -DarchetypeArtifactId=aws-serverless-springboot-archetype \
       -DarchetypeVersion=1.1 
```

And running the project (via. sam local start-api --template sam.yaml --debug) results in the following error:

```
START RequestId: 9e5a7678-5dda-49a2-b244-1337d775ffa2 Version: $LATEST
java.lang.ClassNotFoundException: com.example.StreamLambdaHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
```

This seems to be an issue specifically with Ubuntu sam/docker (Possibly also with ubuntu version 18.04 specifically). Running the same sam-cli 0.3.0 and docker 18.03.1-ce on OSX works correctly and a response is returned as expected.

**Comment by sisiguo** [comment] 2018-06-06 18:36
+1

I'm also running into a similar issue and have a ticket open on the aws-serverless-java-container project here too: https://github.com/awslabs/aws-serverless-java-container/issues/153

But I also encounter the same error when I do a deploy of the package to aws lambda via cloudFormation.

**Comment by abidk** [comment] 2018-06-06 19:14
@sisiguo thanks for mentioning your ticket aswell. What operating system are you running it in?

**Comment by sisiguo** [comment] 2018-06-06 20:12
I'm working off Ubuntu in a VMware box w/ this set-up:

- Ubuntu: 16.0.4
- Docker: 18.03.1-ce
- Sam: 0.3.0

**Comment by mhball** [comment] 2018-06-13 23:07
+1 here too on:

Linux Mint 18.1 Cinnamon 64-bit
Sam  0.3.0
Docker 18.03.1-ce

This is really slowing down our development!

**Comment by fl3x1324** [comment] 2018-06-14 14:10
I've created [pull request](https://github.com/awslabs/aws-sam-cli/pull/480/commits/2fe684d6e3c85bebf6805a6c8de1c9e30afd6684).

**Comment by jfuss** [comment] 2018-06-14 14:29
dupe of #389, which is being addressed in #464?

**Comment by fl3x1324** [comment] 2018-06-14 14:35
@jfuss not really. The permissions for files inside the temp dir are preserved, but the dir itself is 700 which prevents docker from accessing the files inside. Setting the permissions to 755 or something similar eg. xx[4,5,6,7] works fine.

**Comment by fl3x1324** [comment] 2018-06-14 14:38
@jfuss please note that this is not recursive chmod-ing, just the temp dir (tmpXXXXXX). Cheers!

**Comment by fl3x1324** [comment] 2018-06-14 16:11
Problem is in the tempfile.mkdtemp() function where the dir is created with permissions 700, check this out, it's in the python2.7 source:
tempfile.py
```
def mkdtemp(suffix="", prefix=template, dir=None):
    """User-callable function to create and return a unique temporary
    directory.  The return value is the pathname of the directory.

    Arguments are as for mkstemp, except that the 'text' argument is
    not accepted.

    The directory is readable, writable, and searchable only by the
    creating user.

    Caller is responsible for deleting the directory when done with it.
    """

    if dir is None:
        dir = gettempdir()

    names = _get_candidate_names()

    for seq in xrange(TMP_MAX):
        name = names.next()
        file = _os.path.join(dir, prefix + name + suffix)
        try:
            _os.mkdir(file, 0700)
            return file
        except OSError, e:
            if e.errno == _errno.EEXIST:
                continue # try again
            if (_os.name == 'nt' and e.errno == _errno.EACCES and
                _os.path.isdir(dir) and _os.access(dir, _os.W_OK)):
                # On windows, when a directory with the chosen name already
                # exists, EACCES error code is returned instead of EEXIST.
                continue
            raise

    raise IOError, (_errno.EEXIST, "No usable temporary directory name found")

```

**Comment by sanathkr** [comment] 2018-06-14 17:36
@fl3x1324 Looks like my PR won't solve this problem. Giving 755 permissions to the temp directory doesn't harm and probably helps with read/writability of the folder from within the Docker.

Reviewing your PR

**Comment by jfuss** [comment] 2018-06-19 13:07
The fix for this that @fl3x1324 did was release in [v0.4.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.4.0). 

Closing this issue

**Closed by jfuss** 2018-06-19 13:07 UTC
Labels: area/docker, stage/in-progress

**Comment by DanDevine** [comment] 2018-08-24 19:53
I recognize that this bug has been closed with the fix above, but I think I'm experiencing this same issue currently on OS X v0.5.0.  Any insights?  Anything to check/verify locally?
