### ISSUE TITLE
Cache and reuse Docker containers (Warm Start)

### ISSUE THREAD

**Issue by heri16** [awslabs/aws-sam-cli#421] opened 2018-05-19 09:06 UTC
Currently a new Docker container is created and cleanup on every request to the local api gateway, which means a cold start.

We need a better mechanism to cache and reuse containers so we don't take the performance penalty that causes bad latency on every request, similar to warm start.

**Comment by jfuss** [comment] 2018-05-21 13:49
Duplicate of #239 Closing

**Closed by jfuss** 2018-05-21 13:49 UTC
Labels: type/duplicate
