### ISSUE TITLE
API Gateway wrong Stage after deployement

### ISSUE THREAD

**Issue by barroij** [awslabs/aws-sam-cli#1011] opened 2019-02-15 14:10 UTC
### Description

When I create a `AWS::Serverless::Api` and give it a StageName "dev", there are actually to stages that are created for my API Gateway : "Stage" and "dev". Moreover, this is stage "Stage" that gets deployed. 

### Steps to reproduce

Put an API in a template that starts with
`````
CalcApi:
  Type: AWS::Serverless::Api
  Properties:
    StageName: "dev"
`````
### Observed result

- In the API Gateway console, there are 2 stages, and the dashboard tells me that the deployed stage is "Stage"

- If I go in the CloudFormation console, and look at the processed template, there is only one ressource of type `AWS::ApiGateway::Stage` with name "StageName" : "dev", as epxected, but there is also one `AWS::ApiGateway::Deployment` ressource with name "StageName" : "Stage"

![image](https://user-images.githubusercontent.com/17083144/52861744-b9b12c00-3133-11e9-805e-f7862d256db5.png)

### Expected result

I would expect only one stage for my API and, at least, that the stage I specified in my template is the one that gets deployed

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Win 10 Pro
2. `sam --version`: SAM CLI, version 0.11.0

**Comment by jfuss** [comment] 2019-04-23 17:06
Duplicate of https://github.com/awslabs/serverless-application-model/issues/191

This is a SAM Spec known issue. You can follow the issue I linked.

Closing as this related to SAM Spec and not the cli

**Closed by jfuss** 2019-04-23 17:06 UTC
