### ISSUE TITLE
Specify globals in --env-vars file will disable Variables in function

### ISSUE THREAD

**Issue by chandlersong** [awslabs/aws-sam-cli#1817] opened 2020-02-23 14:15 UTC
### Description
#1045 it can work, but it will disable function level variables. I just modify  the go hello word.

envs.json  with Parameters, in lambda,  `SOME_VAR` will be **data**, which is define in the template, it seems it has been disabled

``` json
{
  "HelloWorldFunction": {
    "SOME_VAR": "123",
    "NOT_EXISTS_IN_TEMPLATE": "true"
  },
  "Parameters": {
    "GLOBAL_VAR": "local"
  }
}
```

envs.json  with Parameters, in lambda,  `SOME_VAR` will be **123**,

``` json
{
  "HelloWorldFunction": {
    "SOME_VAR": "123",
    "NOT_EXISTS_IN_TEMPLATE": "true"
  }
}
```

and the template file
```yml
Globals:
  Function:
    Timeout: 60
    Environment:
      Variables:
        GLOBAL_VAR: gobal
Parameters:
  SomeVar:
    Type: String
    Description: My SomeVar
    Default: data
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: aws-lambda/
      Handler: aws-lambda
      Runtime: go1.x
      Tracing: Active
      Events:
        API:
          Type: Api 
          Properties:
            Path: /first
            Method: GET
      Environment: 
        Variables:
          PARAM1: VALUE
          SOME_VAR: !Ref SomeVar
```

in the lambda
I use os.Getenv("SOME_VAR") get the value

**Comment by sriram-mv** [comment] 2020-02-26 18:09
Thanks for the issue! Since this is closely related to #1045, I'm closing it here and continue to track it there.

**Closed by sriram-mv** 2020-02-26 18:09 UTC

**Comment by chandlersong** [comment] 2020-02-27 15:19
it's not relative to #1045. it's a new bug.

#1045 is how to set global variable  in env.json

the this is a bug that use #1045 solution while cause  function level  variable won't work.

**Comment by jfuss** [comment] 2020-02-27 16:25
@chandlersong This is not a bug. The current way we support the `--env-vars` is what you are experiencing, that is you cannot mix the two fields and you need to use one or the other. We will track that request as apart of #1045

**Comment by chandlersong** [comment] 2020-02-27 23:11
I don't you how you define  a bug, but for the common sense,  wired behavior is  a bug.  because we  writing code to make people life easier, not to make people life wired.

consider the completed situation you made  which you call it's normal.

you are working on an application which has 10 lambda, you want some variable share, like use local dynamodb or not. other variable are only for one lambda. you will have only 3 solutions to do this.

1. copy the main template.yml to template_local.yml, change the variable. and merge them every time the origin one change.
2. define all the variable at parameter. it will be very long list.
3. define the shared variable ten times in each function part.
