### ISSUE TITLE
Python event['Origin'] corresponds to event['origin'] on API Gateway

### ISSUE THREAD

**Issue by poidl** [awslabs/aws-sam-cli#479] opened 2018-06-14 06:36 UTC
**Description:**

I use Python and access APIG's event['headers']['origin'] in the handler to manage CORS. I noticed that this corresponds to event['Origin'] (note the capital letter) in the sam-cli. Inconsistent?

**Steps to reproduce the issue:**
Write a python handler with condition 
```
if 'origin' in event['headers']:
 ...
```
and send a request with "Origin" header. 

**Observed result:**

Condition is true using APIG and false using sam-cli. 

**Expected result:**

Condition is true using both APIG and sam-cli. 

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

**Output of `sam --version`**:

SAM CLI, version 0.3.0

**Comment by poidl** [comment] 2018-06-15 11:15
Sorry in the title it should say event['headers']['origin'].

**Comment by jfuss** [comment] 2018-06-18 13:19
@poidl I am not seeing this behavior in APIGW. If you send a request with a "Origin" header, you will get "Origin" as the key in the event['headers'] object. APIGW passes this information through.

Headers are also case-insensitive, so you should be normalizing header keys in your code before comparison. 

Closing as this is not a bug with SAM CLI.

**Closed by jfuss** 2018-06-18 13:19 UTC
Labels: area/local/start-api

**Comment by poidl** [comment] 2018-06-18 20:30
>>Headers are also case-insensitive, so you should be normalizing header
keys in your code before comparison.

Good to know. Thanks
