### ISSUE TITLE
sam build -b . deletes directory

### ISSUE THREAD

**Issue by joxtoyod** [awslabs/aws-sam-cli#1394] opened 2019-09-02 04:16 UTC
Thought it might necessary to have some check/confirmation before proceeding when specifying the build path.

if you invoke the command `sam build -b .` by accident it will clear the entire directory including .git folder

**Comment by TheSriram** [comment] 2019-09-03 16:49
This is related to https://github.com/awslabs/aws-sam-cli/issues/1157

**Comment by jfuss** [comment] 2019-09-11 20:22
Closing as this is a duplicate of #1157

**Closed by jfuss** 2019-09-11 20:22 UTC
Labels: area/build, type/ux, ux/feedback
