### ISSUE TITLE
SAM Local Fatal Error running start-api on Windows 10

### ISSUE THREAD

**Issue by andrewryan1906** [awslabs/aws-sam-cli#336] opened 2018-03-23 08:52 UTC
I've got a lambda function behind an API gateway, powered with a yaml template and a Swagger file. I've got the SAM local started, but when I invoke a function, I get this error:

2018/03/23 04:45:21 Error invoking nodejs6.10 runtime: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/d/orion/services/crm/individual/read.js\\\" to rootfs \\\"/var/lib/docker/overlay2/68255cdc956f38f
e5c99796c8cb9ad6cc80137d449bf8404a0559eb4bbfb38b2/merged\\\" at \\\"/var/lib/docker/overlay2/68255cdc956f38fe5c99796c8cb9ad6cc80137d449bf8404a0559eb4bbfb38b2/merged/var/task\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

Stuck, please help!

Thanks,
Andrew

**Comment by michaelj-smith** [comment] 2018-03-28 19:56
There is some help available in the docs here:
https://github.com/awslabs/aws-sam-local#remote-docker

Double-check your docker "sharing" settings to make sure that the C:\ drive is shared. Your error message seems to indicate that you're working on your D:\ drive, so that may introduce some complications.

Additionally, I've given these instructions to my engineers with Windows:

> On Windows, if running the AWS lambda function/projects on WSL, to get your file directories mounted into the docker containers, you may need to mount the `C:` drive on `/c`, following these steps:
> - Open Docker settings and set your C drive to "Shared"
> - Open a Linux prompt and execute the following:
> ```
> $ sudo mkdir /c
> $ sudo mount --bind /mnt/c /c
> $ cd /c/path/to/project
> ```
> 
> You can auto-mount C: at /c if you run this:
> ```
> sudo echo "/mnt/c /c none bind" >> /etc/fstab
> ```
> 
> On Windows, you'll also need to put this in your ~/.bashrc
> ```
> # Docker on Windows/Host
> export DOCKER_HOST=tcp://127.0.0.1:2375
> ```
> 
> There may be another way as well using `wsl.conf`... but it looks like that doesn't work until build 17093.

This platform is constantly changing each month, so it's hard to keep up with it. I can't guarantee that these instructions are current, but hopefully they will help. I can confirm that the current SAM Local tools are fully capable of running in WSL.

**Comment by bottemav** [comment] 2018-03-30 20:16
I have a similar error message when I invoke a Node.js Lambda function on my Windows. Invoking a Lambda function written in Java succeeds.

**Comment by sanathkr** [comment] 2018-06-01 00:39
Looks like there are a a few potential solutions but the original poster hasn't responded with their specific problem. Closing this. Feel free to re-open if problem persists

**Closed by sanathkr** 2018-06-01 00:39 UTC
