### ISSUE TITLE
Package reporting WinError 2 - The system cannot find the file specified

### ISSUE THREAD

**Issue by willkara** [awslabs/aws-sam-cli#614] opened 2018-08-11 14:07 UTC
**Description:**

When trying to run a package command:

`sam package --template-file template.yaml --output-template-file serverless.yaml --s3-bucket ***name***`

I'm getting the following stacktrace

```
C:\Users\wkara\Resilio Sync\Development\Projects\PyumIpsum\PyumIpsumLambda> sam package --template-file template.yaml --output-template-file serverless.yaml --s3-bucket pyumipsum-code
Traceback (most recent call last):
  File "C:\Users\wkara\AppData\Local\Programs\Python\Python36\Scripts\sam-script.py", line 11, in <module>
    load_entry_point('aws-sam-cli==0.5.0', 'console_scripts', 'sam')()
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\site-packages\samcli\commands\package\__init__.py", line 22, in cli
    do_cli(args)  # pragma: no cover
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\site-packages\samcli\commands\package\__init__.py", line 26, in do_cli
    execute_command("package", args)
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\site-packages\samcli\lib\samlib\cloudformation_command.py", line 17, in execute_command
    subprocess.check_call([aws_cmd, 'cloudformation', command] + list(args))
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\users\wkara\appdata\local\programs\python\python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I can confirm the template.yaml file is there, but it's still giving me this error. Just to be safe, I uninstalled and reinstalled Python3.6.6 and reinstalled aws-sam-cli using pip.

**Steps to reproduce the issue:**
1. Go into directly containing template.yaml file
2. Attempt to package everything
3.

**Observed result:**
File not found error occurs

**Expected result:**
Packaged succesfully

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

- Windows 10
- Python3.6.6

**Output of `sam --version`**:
SAM CLI, version 0.5.0

**Optional Debug logs**:

See Stacktrace above

`Add --debug flag to command you are running`

I've attached an image of my directory structure and my template.yaml file.

**Comment by willkara** [comment] 2018-08-11 14:08
![templatesnip](https://user-images.githubusercontent.com/3278887/43992587-80002dae-9d4e-11e8-842b-1ab8081aa6e2.PNG)
![pyumsnip](https://user-images.githubusercontent.com/3278887/43992588-80095438-9d4e-11e8-8076-6baa5a8b2d6d.PNG)

**Comment by willkara** [comment] 2018-08-11 14:13
I've even tried creating a new, from scratch app using **sam init** and the same error occurs.

**Comment by heitorlessa** [comment] 2018-08-11 15:06
William - Could you please double check if you have AWS CLI installed?

Also, if you could share debug information (—debug) that would help
pinpoint the issue.

**Comment by willkara** [comment] 2018-08-11 16:29
Weird, I substituted

`sam package`

for

`aws cloudformation package`

and it worked :/

**Comment by jfuss** [comment] 2018-08-13 13:03
On windows, we have an assumption about what the [`aws cli` command is](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/lib/samlib/cloudformation_command.py#L16). The error you are seeing is due to this failing and not being able to find that command.

Closing this as a duplicate of #581 and #415

**Closed by jfuss** 2018-08-13 13:03 UTC
