### ISSUE TITLE
custom authorizer not supported when running locally

### ISSUE THREAD

**Issue by ericofusco** [awslabs/aws-sam-cli#945] opened 2019-01-18 12:07 UTC
### Description

I have a custom lambda authorizer configured via swagger and the authorizer is not called before calling the lambda.

### Steps to reproduce

I have the following swagger definition.

```
        swagger: 2.0
        info:
          version: 1.0
          title: !Sub ${Service}-${Stage}
        host: !Ref Domain
        schemes:
        - https
        x-amazon-apigateway-request-validators:
          basic:
            validateRequestBody: true
            validateRequestParameters: true
        paths:
          /credentials/{account}/{role}:
            get:
              responses: {}
              x-amazon-apigateway-request-validator: "basic"
              x-amazon-apigateway-integration:
                uri: !Sub "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CredentialsFunction.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                # The HTTP method used in the integration request. For Lambda function invocations, the value must be POST.
                httpMethod: "POST"
                type: "aws_proxy"
        securityDefinitions:
          TokenAuth:
            type: "apiKey"
            name: "Authorization"
            in: "header"
            x-amazon-apigateway-authtype: "custom"
            x-amazon-apigateway-authorizer:
              authorizerUri: !Sub "arn:${AWS:Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthFunction.Arn}/invocations"
              authorizerResultTtlInSeconds: 0
              identityValidationExpression: ^Bearer [-0-9a-zA-Z\._]*$
              type: "token"
        x-amazon-apigateway-gateway-responses:
          DEFAULT_4XX:
            statusCode: 404
            responseTemplates:
              application/json: "{ \"message\": \"Not Found\" }\n"
          ACCESS_DENIED:
            statusCode: 403
            responseTemplates:
              application/json: "{ \"message\": \"$context.authorizer.message\" }\n"
```

Run `sam local start-api`

Make the request to the endpoint with an invalid token.

```
curl -H "Authorization: Bearer 1234d123.123213d123.123123d1" http://127.0.0.1:3000/credentials/12345/test
```

### Observed result

```
2019-01-18 10:23:10 Constructed String representation of Event to invoke Lambda. Event: {"httpMethod": "GET", "body": null, "resource": "/credentials/{account}/{role}", "requestContext": {"resourceId": "123456", "apiId": "1234567890", "resourcePath": "/credentials/{account}/{role}", "httpMethod": "GET", "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef", "accountId": "123456789012", "stage": "prod", "identity": {"apiKey": null, "userArn": null, "cognitoAuthenticationType": null, "caller": null, "userAgent": "Custom User Agent String", "user": null, "cognitoIdentityPoolId": null, "cognitoAuthenticationProvider": null, "sourceIp": "127.0.0.1", "accountId": null}, "extendedRequestId": null, "path": "/credentials/{account}/{role}"}, "queryStringParameters": null, "headers": {"Host": "127.0.0.1:3000", "User-Agent": "curl/7.54.0", "Accept": "*/*", "Authorization": "Bearer 1234d123.123213d123.123123d1", "X-Forwarded-Proto": "http", "X-Forwarded-Port": "3000"}, "pathParameters": {"account": "12345", "role": "test"}, "stageVariables": null, "path": "/credentials/12345/test", "isBase64Encoded": false}
2019-01-18 10:23:10 Found one Lambda function with name 'CredentialsFunction'
2019-01-18 10:23:10 Invoking handler.get_creds (python3.6)
2019-01-18 10:23:10 Environment variables overrides data is standard format
2019-01-18 10:23:10 Loading AWS credentials from session with profile 'default'
2019-01-18 10:23:10 Resolving code path. Cwd=/Users/ericofusco/projects/gatekeeper, CodeUri=./src
2019-01-18 10:23:10 Resolved absolute path to code is /Users/ericofusco/projects/gatekeeper/src
2019-01-18 10:23:10 Code /Users/ericofusco/projects/gatekeeper/src is not a zip/jar file
2019-01-18 10:23:10 DependencyLayer is a local Layer in the template
2019-01-18 10:23:10 Resolving code path. Cwd=/Users/ericofusco/projects/gatekeeper, CodeUri=/Users/ericofusco/projects/gatekeeper/layers/dependencies
2019-01-18 10:23:10 http://localhost:None "GET /v1.35/images/samcli/lambda:python3.6-6cc89eee1a3853a67c100caab/json HTTP/1.1" 200 None
2019-01-18 10:23:10 Building image...
2019-01-18 10:23:12 Looking for auth config
2019-01-18 10:23:12 Looking for auth entry for 'https://446424624168.dkr.ecr.us-east-1.amazonaws.com'
2019-01-18 10:23:12 Looking for auth entry for 'https://553775872017.dkr.ecr.us-east-1.amazonaws.com'
2019-01-18 10:23:12 Sending auth config ('https://446424624168.dkr.ecr.us-east-1.amazonaws.com', 'https://553775872017.dkr.ecr.us-east-1.amazonaws.com', '553775872017.dkr.ecr.us-east-1.amazonaws.com', '446424624168.dkr.ecr.us-east-1.amazonaws.com')
2019-01-18 10:23:12 http://localhost:None "POST /v1.35/build?t=samcli%2Flambda%3Apython3.6-6cc89eee1a3853a67c100caab&q=False&nocache=False&rm=True&forcerm=False&pull=True HTTP/1.1" 200 None
2019-01-18 10:23:16 http://localhost:None "GET /v1.35/images/201fb73b6dc2/json HTTP/1.1" 200 None
2019-01-18 10:23:16 Trying paths: ['/Users/ericofusco/.docker/config.json', '/Users/ericofusco/.dockercfg']
2019-01-18 10:23:16 Found file at path: /Users/ericofusco/.docker/config.json
2019-01-18 10:23:16 Found 'auths' section
2019-01-18 10:23:16 Auth data for https://446424624168.dkr.ecr.us-east-1.amazonaws.com is absent. Client might be using a credentials store instead.
2019-01-18 10:23:16 Auth data for https://553775872017.dkr.ecr.us-east-1.amazonaws.com is absent. Client might be using a credentials store instead.
2019-01-18 10:23:16 Auth data for 553775872017.dkr.ecr.us-east-1.amazonaws.com is absent. Client might be using a credentials store instead.
2019-01-18 10:23:16 Auth data for 446424624168.dkr.ecr.us-east-1.amazonaws.com is absent. Client might be using a credentials store instead.
2019-01-18 10:23:16 Found 'credsStore' section
2019-01-18 10:23:16 http://localhost:None "GET /v1.35/images/samcli/lambda:python3.6-6cc89eee1a3853a67c100caab/json HTTP/1.1" 200 None
2019-01-18 10:23:16 Requested to skip pulling images ...

2019-01-18 10:23:16 Mounting /Users/ericofusco/projects/gatekeeper/src as /var/task:ro inside runtime container
2019-01-18 10:23:16 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 201 90
2019-01-18 10:23:16 http://localhost:None "GET /v1.35/containers/b5beb370f4989e5faf428b9ab3344ddaec3086fb96d81df0b993c9f400bb55a0/json HTTP/1.1" 200 None
2019-01-18 10:23:16 http://localhost:None "GET /v1.35/containers/b5beb370f4989e5faf428b9ab3344ddaec3086fb96d81df0b993c9f400bb55a0/json HTTP/1.1" 200 None
2019-01-18 10:23:17 http://localhost:None "POST /v1.35/containers/b5beb370f4989e5faf428b9ab3344ddaec3086fb96d81df0b993c9f400bb55a0/start HTTP/1.1" 204 0
2019-01-18 10:23:17 Starting a timer for 30 seconds for function 'CredentialsFunction'
2019-01-18 10:23:17 http://localhost:None "GET /v1.35/containers/b5beb370f4989e5faf428b9ab3344ddaec3086fb96d81df0b993c9f400bb55a0/json HTTP/1.1" 200 None
2019-01-18 10:23:17 http://localhost:None "POST /containers/b5beb370f4989e5faf428b9ab3344ddaec3086fb96d81df0b993c9f400bb55a0/attach?stdout=1&stderr=1&logs=1&stream=1&stdin=0 HTTP/1.1" 101 0
START RequestId: 5726c80f-d11b-49ee-85f1-18336b6914c2 Version: $LATEST
'authorizer': KeyError
Traceback (most recent call last):
  File "/var/task/handler.py", line 13, in get_creds
    username = event['requestContext']['authorizer']['principalId']
KeyError: 'authorizer'

END RequestId: 5726c80f-d11b-49ee-85f1-18336b6914c2
REPORT RequestId: 5726c80f-d11b-49ee-85f1-18336b6914c2 Duration: 284 ms Billed Duration: 300 ms Memory Size: 128 MB Max Memory Used: 36 MB
2019-01-18 10:23:18 http://localhost:None "GET /v1.35/containers/b5beb370f4989e5faf428b9ab3344ddaec3086fb96d81df0b993c9f400bb55a0/json HTTP/1.1" 200 None
2019-01-18 10:23:18 http://localhost:None "DELETE /v1.35/containers/b5beb370f4989e5faf428b9ab3344ddaec3086fb96d81df0b993c9f400bb55a0?v=False&link=False&force=True HTTP/1.1" 204 0
2019-01-18 10:23:18 No Content-Type given. Defaulting to 'application/json'.
2019-01-18 10:23:18 127.0.0.1 - - [18/Jan/2019 10:23:18] "GET /credentials/12345/test HTTP/1.1" 200 -
```

Token is invalid but it called the lambda behind the endpoint showing the authorizer wasn't called, authorizer data not available in the requestContext.

### Expected result

Custom authorizer called before calling lambda behind endpoint.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 10.14.2 (Mojave)
2. SAM CLI, version 0.10.0

**Comment by ericofusco** [comment] 2019-01-18 12:17
Sorry for the wrong ticket (can't delete it. 😅 )

**Comment by jfuss** [comment] 2019-01-25 16:31
Closing as it is a duplicate of #223

**Closed by jfuss** 2019-01-25 16:31 UTC
