### ISSUE TITLE
Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by SamHashemiCA** [awslabs/aws-sam-cli#1613] opened 2019-11-27 18:51 UTC
**Describe the bug**
Hi All,

I'm trying to build a Lambda Function using PyCharm AWS Toolkit and I receive this error which I couldn't track down:
```
Build Failed
Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: ''
```
**To reproduce**
fail to run both [local] and [remote] for a simple helloworld teplate

**Screenshots**
![Screenshot from 2019-11-26 11-40-50](https://user-images.githubusercontent.com/28886954/69667570-189cbd80-1043-11ea-80c3-bc01fc5f0673.png)

**Your Environment**
 - OS: Ubuntu 18.04
 - JetBrains' Product: Pro
 - JetBrains' Product Version: 2019.2.5
 - Toolkit Version: 4.4 
 - SAM CLI Version: 0.33.1
 - Python Version: 3.6

**Comment by jfuss** [comment] 2019-11-27 18:56
@SamHashemiCA This is a duplicate of: https://github.com/awslabs/aws-lambda-builders/issues/135

Basically, the Python version you are using does not have pip installed within it. You will want to install pip into that version.

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3.6 get-pip.py --user
```

Closing this as a duplicate of the aws-lambda-builders issues

**Closed by jfuss** 2019-11-27 18:56 UTC

**Comment by SamHashemiCA** [comment] 2019-11-27 19:02
Great! Thanks @jfuss

**Comment by tbennett0** [comment] 2019-12-05 22:33
@jfuss I seem to be hitting this on building only one of multiple functions (which has an empty requirements.txt, but others do as well) when using the Docker Hub image python:3.7-buster. I've checked, pip is installed and the command specified in the other issue works.

Any ideas? Thanks 👍

**Comment by tbennett0** [comment] 2019-12-05 22:41
Ah. Solved my own issue, I forgot I hadn't migrated this function from 2.7 yet and this container image doesn't have pip installed for 2.7. Your solution works.

Thanks!

**Comment by sukjoonhong** [comment] 2019-12-10 04:24
Hello I got the similar problem.
but if I try to build in console, it works
![question1](https://user-images.githubusercontent.com/52904891/70494808-13199a00-1b50-11ea-81a0-4d0318e2dcc7.png)

but when I try to build my projects through jetbrains AWS Toolkit, it failed to build. what is the problem?
![question2](https://user-images.githubusercontent.com/52904891/70494898-64298e00-1b50-11ea-84ec-3fd0a56046ae.png)

my python version is 2.7

**Comment by tbennett0** [comment] 2019-12-11 16:18
@sukjoonhong not sure, but I'd recommend checking that the Python in the console and the Python used by the AWS toolkit are the same or that both have pip installed in 2 & 3.
