### ISSUE TITLE
Lambda invoke module import error 

### ISSUE THREAD

**Issue by TCreuillenet** [awslabs/aws-sam-cli#193] opened 2017-11-09 11:18 UTC
Hi 
i'm actually trying to use basic functions (Python/Nodejs) from sam with sample functions `sam local invoke HelloWorldFunction -e event.json` but here is my errror :
`{"errorMessage": "Unable to import module 'main'"}`
The Handler naming is good : `main.handler`
I've been trying to run lambda in different ways, reinstalling sam, debug but i can't figure out what happens..

For your information, i run it with Windows 10 / sam 0.2.2. Do you have a piece of answer ?

Thanks !

**Comment by PaulMaddox** [comment] 2017-11-25 11:15
Hi @TCreuillenet, can you paste the contents of your `main.js` file, or provide a reproducable test case so that we can investigate further?

**Comment by lancha90** [comment] 2018-01-03 14:23
i have the same issue

**Comment by xkguq007** [comment] 2018-01-19 04:56
I have the same issue too, I'm using typescript.

**Comment by sanathkr** [comment] 2018-05-31 23:51
You should set the CodeUri to a directory that contains your node_modules directory. SAM CLI will mount the directory pointed by CodeUri into the Docker container. It doesn't have any smarts to detect your node_modules or transpile Typescript to JS. 

Closing this issue as a dupe of #125

**Closed by sanathkr** 2018-05-31 23:51 UTC
