### ISSUE TITLE
sam deploy --no-fail-on-empty-changeset no longer working on version 0.33

### ISSUE THREAD

**Issue by glenserraview** [awslabs/aws-sam-cli#1600] opened 2019-11-26 03:56 UTC
Previously I have used sam deploy with the flag --no-fail-on-empty-changeset to not throw an error if a stack is deployed with no changes.

This switch does not work on version 0.33 any more, giving an error:

Error: no such option: --no-fail-on-empty-changeset

**Comment by blutter** [comment] 2019-11-26 04:26
I experienced the same issue this morning.

It looks like `--no-fail-on-empty-changeset` has been removed but `--fail-on-empty-changeset` is still there.

https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/commands/deploy/command.py#L119

**Comment by glenserraview** [comment] 2019-11-26 05:45
I don't think the --fail-on-empty-changeset is going to help though, since I can't say --fail-on-empty-changeset=false (or similar). Unless I've missed something.

**Comment by orrmor94** [comment] 2019-11-26 09:45
+1
experiencing the same issue, and --fail-on-empty-changeset is not helping (and that's the default behavior)

**Comment by plantusd** [comment] 2019-11-26 14:38
sam issue
`Usage: sam deploy [OPTIONS]
Try "sam deploy --help" for help.

Error: no such option: --no-fail-on-empty-changeset`

However, this might  not be a bug, because, in the documentation, this flag diapered 
![image](https://user-images.githubusercontent.com/44056339/69642878-1cdcd100-106b-11ea-8b4d-4c5f7c9e3881.png)

**Comment by jfuss** [comment] 2019-11-26 20:50
Thank you all for the report. This was a miss during our porting of deploy off of AWS CLI and other improvement work on the command. This was fixed in #1607, which should be rolled up into our next release. Updating labels

**Comment by jfuss** [comment] 2019-11-27 15:03
This was released yesterday with [v0.34.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.34.0).

Closing

**Closed by jfuss** 2019-11-27 15:03 UTC
Labels: area/deploy, stage/waiting-for-release, type/bug

**Comment by jamesseanwright** [comment] 2022-05-24 12:37
I'm facing a related issue across both v1.24.1 and v1.50.0, where the flag exists but the deployment fails with:

```sh
Error: No changes to deploy. Stack $STACK_NAME is up to date
```

Specifying the `--no-fail-on-empty-changeset` flag should surely result in the CLI returning a `0` exit code in this scenario. Please can you advise @jfuss?

**Comment by moelasmar** [comment] 2022-06-01 06:08
Hello @jamesseanwright, 
I tried to reproduce this issue using version 1.50.0, but I could not.
I executed the following flow on a sample hello_world application:
```
% sam --version
SAM CLI, version 1.50.0

% sam deploy -g

....
Waiting for changeset to be created..
......

Changeset created successfully. 

2022-06-01 06:02:20 - Waiting for stack create/update to complete

Successfully created/updated stack - api-stack-2 in us-east-1

% sam deploy --no-fail-on-empty-changeset
File with same data already exists at api-stack-2/9b6de589c6090977344ed6c0be842b21, skipping upload

	Deploying with following values
	===============================
	Stack name                   : api-stack-2
	Region                       : us-east-1
	Confirm changeset            : False
	Disable rollback             : False
	Deployment s3 bucket         : aws-sam-cli-managed-default-samclisourcebucket-1jkmnoixl6hj1
	Capabilities                 : ["CAPABILITY_IAM"]
	Parameter overrides          : {}
	Signing Profiles             : {}

Initiating deployment
=====================
File with same data already exists at api-stack-2/c3a2a88c9f61a6cd16a5a68edcf84105.template, skipping upload

Waiting for changeset to be created..
No changes to deploy. Stack api-stack-2 is up to date

% echo $?                                
0
```
Could you please share how did you execute the `deploy` command, and if it is possible to share the logs in debug mode with us to investigate more.

**Comment by jamesseanwright** [comment] 2022-06-06 09:20
Apologies for the delayed reply @moelasmar; I was on annual leave last week.

The exact command we're running is:

```sh
$ sam deploy \
		--debug \
		--stack-name ${STACK_NAME} \
		--capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
		--region ${REGION} \
		--s3-bucket ${S3_BUCKET} \
		--parameter-overrides \
			# [Redacted parameter overrides]
		--no-fail-on-empty-changeset \
		--no-confirm-changeset
```

In our CI pipeline, this gives us:

```sh
Error: No changes to deploy. Stack $STACK_NAME is up to date
make: *** [Makefile:37: deploy] Error 1 # Note we run `sam deploy` via a Makefile target
```

I assume it's the combination of options or some sort of precedence issue that's resulting in `--no-fail-on-empty-changeset` being ignored.

I can provide the full logs with the redacted stack name if that'd help, but the `--debug` flag doesn't (at least in my opinion) surface any additional insights in this instance.

**Comment by jamesseanwright** [comment] 2022-08-16 13:23
@moelasmar Is there any update on this? The issue still persists and is now blocking one of my deployment pipelines.

**Comment by jamesseanwright** [comment] 2022-08-16 13:44
Rather embarrassingly, I've just spotted that the last parameter override (which have been broken down onto individual lines) I'm passing to `sam deploy` isn't suffixed with a backslash, hence the shell interpreter is losing the subsequent arguments 🤦 Really sorry about; I assume this will work, but I'll be in touch if the issue persists.
