### ISSUE TITLE
If sam version v0.16.0, sample function for go1.x does not work 

### ISSUE THREAD

**Issue by goldeneggg** [awslabs/aws-sam-cli#1178] opened 2019-05-15 00:13 UTC
### Description

Sample function of go1.x does not work.

### Steps to reproduce

```
$ sam init --runtime go1.x --name samwork
$ cd samwork
$ go mod init
$ go get github.com/aws/aws-lambda-go@latest
$ GOOS=linux GOARCH=amd64 go build -o hello-world/hello-world hello-world/main.go
$ sam local start-api -p 3000 --debug
$ curl -XGET http://127.0.0.1:3000/hello
{"message":"Internal server error"}
```

### Observed result

```
START RequestId: 2045c6aa-17b0-1aa7-9f52-856ff79a37de Version: $LATEST
END RequestId: 2045c6aa-17b0-1aa7-9f52-856ff79a37de
REPORT RequestId: 2045c6aa-17b0-1aa7-9f52-856ff79a37de  Duration: 784.09 ms     Billed Duration: 800 ms Memory Size: 128 MB     Max Memory Used: 11 MB
2019-05-15 09:01:45 http://localhost:None "GET /v1.35/containers/71bfb4c3f9130eabdbaa74b1340190917a7de9f697a2adf189de28b28eb99639/json HTTP/1.1" 200 None
2019-05-15 09:01:45 http://localhost:None "DELETE /v1.35/containers/71bfb4c3f9130eabdbaa74b1340190917a7de9f697a2adf189de28b28eb99639?v=False&link=False&force=True HTTP/1.1" 204 0
2019-05-15 09:01:45 Invalid API Gateway Response Keys: {'multiValueHeaders'} in {'statusCode': 200, 'headers': None, 'multiValueHeaders': None, 'body': 'Hello, 202.231.92.33\n'}
2019-05-15 09:01:45 Function returned an invalid response (must include one of: body, headers or statusCode in the response object). Response received: {"statusCode":200,"headers":null,"multiValueHeaders":null,"body":"Hello, 202.231.92.33\n"}
2019-05-15 09:01:45 127.0.0.1 - - [15/May/2019 09:01:45] "GET /hello HTTP/1.1" 502 -
```

### Expected result

If sam cli version `<= v0.15.0`, it works correctly.

```
$ sam local start-api -p 3000 --debug
$ curl -XGET http://127.0.0.1:3000/hello
Hello, 202.231.92.33
```

```
START RequestId: e966a3ac-a6b0-1c4a-9c0d-449e67bec5ba Version: $LATEST
END RequestId: e966a3ac-a6b0-1c4a-9c0d-449e67bec5ba
REPORT RequestId: e966a3ac-a6b0-1c4a-9c0d-449e67bec5ba  Duration: 898.63 ms     Billed Duration: 900 ms Memory Size: 128 MB     Max Memory Used: 11 MB
2019-05-15 09:10:14 http://localhost:None "GET /v1.35/containers/6f8c6ec96086faa544aafb002fa556523ae7785957521630fc9764e8fa8a456a/json HTTP/1.1" 200 None
2019-05-15 09:10:14 http://localhost:None "DELETE /v1.35/containers/6f8c6ec96086faa544aafb002fa556523ae7785957521630fc9764e8fa8a456a?v=False&link=False&force=True HTTP/1.1" 204 0
2019-05-15 09:10:14 No Content-Type given. Defaulting to 'application/json'.
2019-05-15 09:10:14 127.0.0.1 - - [15/May/2019 09:10:14] "GET /hello HTTP/1.1" 200 -
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OS X (Mojavi)
2. `sam --version`: `SAM CLI, version 0.16.0`
3. `go version`: `go version go1.12.4 darwin/amd64`
4. version of "github.com/aws/aws-lambda-go" package: v1.10.0

**Comment by goldeneggg** [comment] 2019-05-15 00:34
I created a pr https://github.com/awslabs/aws-sam-cli/pull/1179

**Comment by jfuss** [comment] 2019-05-15 12:00
Duplicate of #830 which has an already active PR #1166 

Closing

**Closed by jfuss** 2019-05-15 12:00 UTC
