### ISSUE TITLE
Local API Gateway responds with Internal Server error

### ISSUE THREAD

**Issue by kaarthikeyansp** [awslabs/aws-sam-cli#191] opened 2017-11-07 10:49 UTC
Hi,

I have tried to execute the sample code from https://github.com/awslabs/aws-sam-local/tree/master/samples/api-event-source 

But facing **{ "message": "Internal server error" }** error when I access **http://127.0.0.1:3000/**

I'm executing in Window 10, so I used --docker-volume-basedir parameter

C:\Users\AWS-SAM-Local\samples\api-event-source>**sam local start-api --docker-volume-basedir \c\Users\AWS-SAM-Local\samples\api-event-source**

2017/11/07 16:14:33 Fetching lambci/lambda:nodejs6.10 image for nodejs6.10 runtime...
nodejs6.10: Pulling from lambci/lambda
Digest: sha256:7eb4ced6a15ae3c30effc4ec0cd3aabb2bd57c9a8330b37920c3d5d722d81083
Status: Image is up to date for lambci/lambda:nodejs6.10

Mounting index.handler (nodejs6.10) at http://127.0.0.1:3000/ [OPTIONS GET HEAD POST PUT DELETE TRACE CONNECT]
Mounting static files from \c\Users\AWS-SAM-Local\samples\api-event-source\public at /

2017/11/07 16:14:47 Invoking index.handler (nodejs6.10)
**_Lambda starts successfully_**
START RequestId: 52d4ca03-a557-1cb1-8695-91e22537a7b2 Version: $LATEST
2017-11-07T10:44:49.656Z        52d4ca03-a557-1cb1-8695-91e22537a7b2    test **_---> log message from Lambda prints successfully_**
END RequestId: 52d4ca03-a557-1cb1-8695-91e22537a7b2
REPORT RequestId: 52d4ca03-a557-1cb1-8695-91e22537a7b2  Duration: 5.91 ms       Billed Duration: 0 ms   Memory Size: 0 MB       Max Memory Used: 28 MB
**_Lambda ends successfully_**

_**2017/11/07 16:14:53 Function index.handler timed out after 3 seconds
2017/11/07 16:14:53 Error invoking nodejs6.10 runtime: io: read/write on closed pipe**_

Problem happens in last 2 lines (I presume), even I tried increasing timeout to 10 seconds, but didn't help

Please let me know what went wrong in this.

Regards,
Kaarthikeyan

**Comment by sejsworld** [comment] 2017-11-09 21:07
I get the same error. Have you found a solution?

**Comment by kaarthikeyansp** [comment] 2017-11-10 05:30
@sejsworld Didn't get any solution yet. Let me know if case you resolved it.

**Comment by diegotry** [comment] 2017-11-11 08:47
Your timeout looks 3s. Try to increase the timeout in your template:

```yaml
Resources:
  DistributeAmiApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 10
      ....
```

**Comment by diegotry** [comment] 2017-11-11 08:48
Resources:
  Products:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 10

**Comment by aureshsaxena** [comment] 2017-12-04 19:04
I tried increasing that to 20, but didn't solved the issue

**Comment by leifulstrup** [comment] 2018-01-17 15:17
edit products.js file, 

_change_ 

let id = event.pathParameters.product || false;

_to_ 

let id = event.pathParameters || false;

**Comment by kekkler** [comment] 2018-02-02 00:42
Increasing timeout has no effect for my particular endpoint.

**Comment by kekkler** [comment] 2018-02-02 21:19
I believe this is a bug; this is not expected behavior. The ```Timeout``` property has no effect whatsoever on when the lambda times out; The timeout always defaults to three seconds.

**Comment by PierrePrimot** [comment] 2018-02-28 16:20
@leifulstrup your suggestion corrects the bug in products.js but still there is no response from SAM.

**Comment by vlamic** [comment] 2018-03-29 10:38
The container seem to ignore the function's Timeout setting and only has a timeout of 3s

**Comment by vlamic** [comment] 2018-04-05 21:37
Apparently it doesn't respect the `Timeout` setting in the `Globals` section. Works fine when specified for each function separately. Verified just now with the latest sam local from master + latest lambci/lambda images.

**Comment by andela-foladeji** [comment] 2018-04-11 14:17
@kavuri have you tried running it in debug mode to find out if the lambda function works properly

**Comment by sanathkr** [comment] 2018-05-31 23:48
This problems happens due to misconfigured SAM template or Lambda function app. I am going to close the issue because this is not a SAM CLI issue

**Closed by sanathkr** 2018-05-31 23:48 UTC

**Comment by debojit777** [comment] 2020-04-26 20:10
> @andela-foladeji Figured out the problem. The reason was because my dynamodb-local was not running in a docker container and sam runs in docker. So I had to run dynamodb-local in docker and add it to the same network as sam
> The timeout error does not help to resolve the problem and had to really debug the whole code to get to the root

i try to run dynamodb-local inside docker by using 
```
docker run -d -p 8000:8000 amazon/dynamodb-local
```

getting error when I  try:
```
aws dynamodb list-tables --endpoint-url http://localhost:8000

Could not connect to the endpoint URL: "http://localhost:8000/"
```
