### ISSUE TITLE
Custom HTTP Headers being stripped when running lambda - sam local start-api

### ISSUE THREAD

**Issue by pstephenmurphy** [awslabs/aws-sam-cli#595] opened 2018-08-03 19:03 UTC
**Description:**
Custom HTTP Headers being stripped when running lambda - sam local start-api

**Steps to reproduce the issue:**
1. Start lambda with `sam local start-api -t template.yaml`
2. Use curl to hit the endpoint (see below)
3. Check the event['headers'] and see that only `Content-Type` is received by the lambda handler

`curl "http://127.0.0.1:3000/v1/presearch?screenId=foo&tab=bar&subtab=bar&venue=MYTT&pageId=bar&skuId=bar&view=bar&locale=en_us&smart=true" \
     -H 'Content-Type: application/json' \
     -H 'authId: 123147053189079' \
     -H 'ticket: V1-28-a3cumsty6j3un2kapj6n1j' \
     -H 'tid: 9319697c-150f-4c03-9315-129784ece46e' \
     -H 'offeringid: e61eb086-cc64-49fa-9eef-0c113ac44d7e'`

**Observed result:**
Missing custom headers

**Expected result:**
All headers passed are received

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Mac OSX 10.13.6

**Output of `sam --version`**:
 0.5.0

**Optional Debug logs**:
JSON of event:
`    {
        "timestamp": "2018-08-03T18:58:19.902576Z",
        "message": "event",
        "host": "de80402d1825",
        "path": "/v1/presearch",
        "tags": ["env=local"],
        "level": "DEBUG",
        "logger": "smart_search",
        "stack_info": null,
        "httpMethod": "GET",
        "body": null,
        "resource": "/v1/presearch",
        "requestContext": {
            "resourceId": "123456",
            "apiId": "1234567890",
            "resourcePath": "/v1/presearch",
            "httpMethod": "GET",
            "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef",
            "accountId": "123456789012",
            "stage": "prod",
            "identity": {
                "apiKey": null,
                "userArn": null,
                "cognitoAuthenticationType": null,
                "caller": null,
                "userAgent": "Custom User Agent String",
                "user": null,
                "cognitoIdentityPoolId": null,
                "cognitoAuthenticationProvider": null,
                "sourceIp": "127.0.0.1",
                "accountId": null
            },
            "extendedRequestId": null,
            "path": "/v1/presearch"
        },
        "queryStringParameters": {
            "tab": "bar",
            "subtab": "bar",
            "venue": "MYTT",
            "pageId": "bar",
            "skuId": "bar",
            "view": "bar",
            "locale": "en_us",
            "smart": "true"
        },
        "headers": {
            "Host": "127.0.0.1:3000",
            "User-Agent": "curl/7.54.0",
            "Accept": "*/*",
            "Content-Type": "application/json",
            "X-Forwarded-Proto": "http",
            "X-Forwarded-Port": "3000"
        },
        "pathParameters": null,
        "stageVariables": null,
        "isBase64Encoded": false
    }
`

**Comment by jfuss** [comment] 2018-08-06 15:01
Running the same template we use for `start-api`, I see the customer headers.

* `samdev local start-api -t tests/integration/testdata/start_api/template.yaml`
* `$ curl "http://127.0.0.1:3000/id/4" -H "authId: 123147053189079"                                                                                                             
{"body": null, "httpMethod": "GET", "resource": "/id/{id}", "queryStringParameters": null, "requestContext": {"httpMethod": "GET", "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef", "path": "/id/{id}", "extendedRequestId": null, "resourceId": "123456", "apiId": "1234567890", "stage": "prod", "resourcePath": "/id/{id}", "identity": {"accountId": null, "apiKey": null, "userArn": null, "cognitoAuthenticationProvider": null, "cognitoIdentityPoolId": null, "userAgent": "Custom User Agent String", "caller": null, "cognitoAuthenticationType": null, "sourceIp": "127.0.0.1", "user": null}, "accountId": "123456789012"}, "headers": {"Host": "127.0.0.1:3000", "X-Forwarded-Proto": "http", "Authid": "123147053189079", "X-Forwarded-Port": "3000", "Accept": "*/*", "User-Agent": "curl/7.43.0"}, "stageVariables": null, "path": "/id/4", "pathParameters": {"id": "4"}, "isBase64Encoded": false}%`
* `curl "http://127.0.0.1:3000/id/4" -H 'authId: 123147053189079'
{"body": null, "httpMethod": "GET", "resource": "/id/{id}", "queryStringParameters": null, "requestContext": {"httpMethod": "GET", "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef", "path": "/id/{id}", "extendedRequestId": null, "resourceId": "123456", "apiId": "1234567890", "stage": "prod", "resourcePath": "/id/{id}", "identity": {"accountId": null, "apiKey": null, "userArn": null, "cognitoAuthenticationProvider": null, "cognitoIdentityPoolId": null, "userAgent": "Custom User Agent String", "caller": null, "cognitoAuthenticationType": null, "sourceIp": "127.0.0.1", "user": null}, "accountId": "123456789012"}, "headers": {"Host": "127.0.0.1:3000", "X-Forwarded-Proto": "http", "Authid": "123147053189079", "X-Forwarded-Port": "3000", "Accept": "*/*", "User-Agent": "curl/7.43.0"}, "stageVariables": null, "path": "/id/4", "pathParameters": {"id": "4"}, "isBase64Encoded": false}%`

We don't mutate the headers at all, (just convert it into a bare bones dict from the Flask specific one): https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/local/apigw/local_apigw_service.py#L276

I would debug your curl command.

Closing as I can't reproduce.

**Closed by jfuss** 2018-08-06 15:01 UTC

**Comment by ahmadshakil** [comment] 2023-11-28 06:44
I had same issue and it was solved when  change case of Header flag name e.g.,  instead of offering > Offering
