### ISSUE TITLE
validate issue

### ISSUE THREAD

**Issue by plantusd** [awslabs/aws-sam-cli#1656] opened 2019-12-11 12:52 UTC
### Description

sam validate fails without region provided

### Steps to reproduce

sam validate

### Observed result

```
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 93, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 27, in cli
    do_cli(ctx, template_file)  # pragma: no cover
  File "/usr/local/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 47, in do_cli
    validator.is_valid()
  File "/usr/local/lib/python3.8/site-packages/samcli/commands/validate/lib/sam_template_validator.py", line 60, in is_valid
    template = sam_translator.translate(sam_template=self.sam_template, parameter_values={})
  File "/usr/local/lib/python3.8/site-packages/samtranslator/translator/translator.py", line 67, in translate
    deployment_preference_collection = DeploymentPreferenceCollection()
  File "/usr/local/lib/python3.8/site-packages/samtranslator/model/preferences/deployment_preference_collection.py", line 41, in __init__
    self.codedeploy_iam_role = self._codedeploy_iam_role()
  File "/usr/local/lib/python3.8/site-packages/samtranslator/model/preferences/deployment_preference_collection.py", line 99, in _codedeploy_iam_role
    ArnGenerator.generate_aws_managed_policy_arn('service-role/AWSCodeDeployRoleForLambda')
  File "/usr/local/lib/python3.8/site-packages/samtranslator/translator/arn_generator.py", line 29, in generate_aws_managed_policy_arn
    return 'arn:{}:iam::aws:policy/{}'.format(ArnGenerator.get_partition_name(),
  File "/usr/local/lib/python3.8/site-packages/samtranslator/translator/arn_generator.py", line 49, in get_partition_name
    region_string = region.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

### Expected result

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: python:3.8-alpine
2. `sam --version`: 0.37.0

`Add --debug flag to command you are running`

**Comment by jfuss** [comment] 2019-12-11 19:26
Duplicate of #442 

Closing

**Closed by jfuss** 2019-12-11 19:26 UTC
