### ISSUE TITLE
Official aws-sam-cli docker image on DockerHub

### ISSUE THREAD

**Issue by drissamri** [awslabs/aws-sam-cli#502] opened 2018-06-24 14:48 UTC
**Description:**
I've been using aws-sam-cli for local development with great succes for Java based application. Now I'm trying to go the next mile and integrate the tool in our CI pipeline, but it would be much easier if there would be an official Docker image that can be used for this purpose. 
It could also be nice for people just starting out with aws-sam-cli and not having to install Python, pip, etc.

I tried to setup my own Docker image but have run into some issues like https://github.com/awslabs/aws-sam-cli/issues/461

**Expected result:**
Official supported image published on https://hub.docker.com/

**Comment by herbowicz** [comment] 2018-06-25 07:59
https://hub.docker.com/r/cnadiminti/aws-sam-local/

**Comment by drissamri** [comment] 2018-06-25 09:55
This is the Dockerfile I based my image on for 0.3.0 and 0.4.0, but did not get this working due to error like issue #461. I can build it again and post the errors here if wanted if you are sure that image is supposed to be working.

**Comment by drissamri** [comment] 2018-06-26 21:16
https://github.com/drissamri/docker-aws-sam-cli

```
docker run -it --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$(PWD)":/var/opt \
    -p "3000:3000" \
    drissamri/docker-aws-sam-cli local start-api --host 0.0.0.0 --docker-volume-basedir "${PWD}"
```

```
2018-06-26 21:11:17 Mounting ReportLambda at http://0.0.0.0:3000/report [POST]
2018-06-26 21:11:17 You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2018-06-26 21:11:17  * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
2018-06-26 21:11:21 Invoking be.drissamri.serverless.ServerlessApplication (java8)
2018-06-26 21:11:21 Starting new HTTP connection (1): 169.254.169.254

Fetching lambci/lambda:java8 Docker container image......
2018-06-26 21:11:24 Mounting /Users/drissamri/workspace/drissamri/aws-serverless-starter/spring-cloud-functions/target/spring-example-1.0.0-aws.jar as /var/task:ro inside runtime container
2018-06-26 21:11:24 Exception on /report [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/180d69acdac8eb55dd22ec7724ec660816db67568e5fd96c333a7d840f609626/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/samcli/local/apigw/service.py", line 185, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream, stderr=self.stderr)
  File "/usr/local/lib/python3.6/site-packages/samcli/commands/local/lib/local_lambda.py", line 80, in invoke
    stdout=stdout, stderr=stderr)
  File "/usr/local/lib/python3.6/site-packages/samcli/local/lambdafn/runtime.py", line 83, in invoke
    self._container_manager.run(container)
  File "/usr/local/lib/python3.6/site-packages/samcli/local/docker/manager.py", line 63, in run
    container.start(input_data=input_data)
  File "/usr/local/lib/python3.6/site-packages/samcli/local/docker/container.py", line 167, in start
    real_container.start()
  File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 374, in start
    return self.client.api.start(self.id, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 1063, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/drissamri/workspace/drissamri/aws-serverless-starter/spring-cloud-functions/target/spring-example-1.0.0-aws.jar\\\" to rootfs \\\"/var/lib/docker/overlay2/46f3256c6cefa3aaf22a15cb6e8a37bf0c64980914621a67e2e021922a63ace3/merged\\\" at \\\"/var/lib/docker/overlay2/46f3256c6cefa3aaf22a15cb6e8a37bf0c64980914621a67e2e021922a63ace3/merged/var/task\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type")
2018-06-26 21:11:24 172.17.0.1 - - [26/Jun/2018 21:11:24] "POST /report HTTP/1.1" 502 -
```

@jfuss @herbowicz any idea?

**Comment by jfuss** [comment] 2018-06-27 13:33
@drissamri You are trying to run docker inside of docker which currently isn't something we support out of the box (and can get very sticky). We already have a feature request for this: #181. I would encourage you to explain your use case in that issue, so everything is in one place.

Closing as a duplicate of #181

**Closed by jfuss** 2018-06-27 13:33 UTC
