### ISSUE TITLE
Successfully message didn't show region

### ISSUE THREAD

**Issue by timoschilling** [awslabs/aws-sam-cli#1704] opened 2020-01-03 12:47 UTC
### Description

If you configure your region via `~/.aws/config`, the `sam deploy` command didn't show the region in the successfully message.`sam` uses this config to resolve the region if you deploy with `--profile`.

### Steps to reproduce

```
# ~/.aws/config
[profile my-profile]
region = eu-central-1
```

`sam deploy --profile my-profile ...`

### Observed result

`Successfully created/updated stack - STACK-NAME in None`

### Expected result

`Successfully created/updated stack - STACK-NAME in eu-central-1`

This result happens if you deploy with:
`sam deploy --profile my-profile --region eu-central-1 ...`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 10.15
2. `sam --version`: 0.39.0

**Comment by c2tarun** [comment] 2020-01-03 18:22
Hi @timoschilling,

Thanks for creating issue with us. I am not able to reproduce the issue.

Here is how my aws/config looks like:
```
[default]
output = json
region = us-west-2
[profile issue-1704]
region = us-west-1
```

I tried to deploy with profile `issue-1704` with command `sam deploy --profile issue-1704 --stack-name issue-1704 --s3-bucket issue-1704 --capabilities CAPABILITY_IAM`

Here is what I get in output:

```
Stack issue-1704 outputs:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
OutputKey-Description                                                                        OutputValue
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
HelloWorldFunctionIamRole - Implicit IAM Role created for Hello World function               arn:aws:iam::99999999999:role/issue-1704-HelloWorldFunctionRole-A4ZZKKPN1RHX
HelloWorldApi - API Gateway endpoint URL for Prod stage for Hello World function             https://ifnysaygd9.execute-api.us-west-1.amazonaws.com/Prod/hello/
HelloWorldFunction - Hello World Lambda Function ARN                                         arn:aws:lambda:us-west-1:99999999999:function:issue-1704-HelloWorldFunction-2XKNYPS4ODOI
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Successfully created/updated stack - issue-1704 in us-west-1
```

Can you please share full deploy command?

**Comment by sriram-mv** [comment] 2020-02-10 19:46
Going to close this issue, please reach out if you are continuing to see this behavior.

**Closed by sriram-mv** 2020-02-10 19:46 UTC
Labels: area/profiles, stage/more-info-needed

**Comment by skyprince999** [comment] 2021-08-28 04:02
@timoschilling were you able to resolve this? I using SAM to deploy a containerized image to Lambda and it gives me a None value. The Lambda function is working locally, but gives a 502 <Bad Gateway Error> on deployment. I was wondering if this may be causing it could also be related to VPC settings.

**Comment by timoschilling** [comment] 2021-08-28 09:00
@skyprince999 no wasn't able to fix it
