### ISSUE TITLE
SAM Decompresses Java ZIP at every Invocation (can't hot start)

### ISSUE THREAD

**Issue by feinstein** [awslabs/aws-sam-cli#1073] opened 2019-03-21 20:01 UTC
I am testing locally a Java Lambda + API Gateway instance. At every invocation SAM decompresses de ZIP package and mounts it into a Docker image, which makes testing VERY slow, since every small query string change will trigger the whole process.

Can't the Docker image be cached, and only be recreated once the ZIP package's File Modification time changes? Or maybe just compute a fast Hash (e.g. CRC32) to check if the ZIP changed at all.

It feels like every HTTP request will trigger a cold start.

**Comment by jfuss** [comment] 2019-03-21 20:22
@feinstein You can point the `CodeUri` to a directory with the source files instead of zipping. Is that an option for you?

**Comment by feinstein** [comment] 2019-03-21 21:50
It's still slow, it doesn't have to decompress anymore, but it still needs to fetch and mount the image at every HTTP Request.

**Comment by feinstein** [comment] 2019-03-21 23:38
@jfuss related to this: can we keep the SAM Local instance running as if it was a hot lambda instance? 

I am asking this because it's very annoying to test this with IntelliJ IDEA, for each HTTP Request I do, I have to send the Request, click the Debug button, wait for it all to connect and hit a breakpoint (it does take a while) and then after the Response is returned the debugger disconnects and I have to do it all over again. It would be a much better experience if the debugger could remain connected to the container and keep getting invocations from HTTP Requests automatically.

**Comment by jfuss** [comment] 2019-03-22 14:18
@feinstein That is expected and is by design currently. A single invoke will create the container (and therefore mount), execute, and then remove the container. This allows the CLI to reload changes to the function code without having to kill and restart the command and keeps the commands stateless. We understand that this is a sharper edge of the CLI and that these interactions can be improved but right now this is the experience. 

You can follow along at #239, which is an issue about the warm start experience.

Closing this as a duplicate of #239 but happy to re-open if there is something not covered.

**Closed by jfuss** 2019-03-22 14:18 UTC

**Comment by feinstein** [comment] 2019-03-22 14:23
I see, well, this is unfortunate, I was moving to SAM Local so I could make my builds simpler and easier to iterate/test... But this is way slower than what I had. Thanks for the support!

**Comment by jfuss** [comment] 2019-03-22 14:47
@feinstein Understood. The team is very aware of this issue and pain point. We are looking at ways to make this better but don't have anything to share at the moment.

**Comment by miparnisari** [comment] 2020-06-02 02:46
@jfuss can you provide an example for 

> @feinstein You can point the CodeUri to a directory with the source files instead of zipping. Is that an option for you?

This works but decompresses every time: `CodeUri: ./target/aws-logs-metricfilter-handler-1.0-SNAPSHOT.jar`

This doesn't work: `CodeUri: ./src/main/java`

`START RequestId: 5654a685-d974-10c1-9f8a-84ec89677cd8 Version: $LATEST
java.lang.ClassNotFoundException: software.amazon.logs.loggroup.HandlerWrapper`
