### ISSUE TITLE
Add support for --profile and --region flags to the "sam validate" command

### ISSUE THREAD

**Issue by piersf** [awslabs/aws-sam-cli#543] opened 2018-07-09 17:48 UTC
**Description:**

The flag `--region` is currently not supported in the `sam validate` command and therefore we have to rely on exporting the AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION environmental variables in case we use a non-default location for the AWS credentials file.
Similar to what the `sam deploy` or `sam package` commands support.

Adding support to the `sam validate` command for `--profile` and `--region` flags would be really helpful and would allow us to avoid exporting the above-mentioned variables.

**Steps to reproduce the issue:**
1. `sam validate -t /path/to/template.yaml --region us-east-1`
2. `sam validate -t /path/to/template.yaml --profile dev`
3. `sam validate -t /path/to/template.yaml --profile dev --region us-east-1`

**Observed result:**
```
sam validate -t /path/to/template.yaml --region us-east-1
Error: no such option: --region

sam validate -t /path/to/template.yaml --profile dev
Error: no such option: --profile
```

**Expected result:**
```
sam validate -t /path/to/template.yaml --profile dev --region us-east-1
 /path/to/template.yaml is a valid SAM Template
```

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
RedHat Linux 7.5
**Output of `sam --version`**:
SAM CLI, version 0.4.0

**Comment by jfuss** [comment] 2018-07-09 17:56
Duplicate of #396

closing

**Closed by jfuss** 2018-07-09 17:56 UTC
