### ISSUE TITLE
duplicate entries in $HOME/.aws/credentials crashes cli

### ISSUE THREAD

**Issue by rojomisin** [awslabs/aws-sam-cli#1035] opened 2019-03-01 22:46 UTC
### Description

If you have duplicate aws profile entries in `$HOME/.aws/credentials` cli app wont work

### Steps to reproduce

copy paste a profile in your $HOME/.aws/credentials 
run cli hello world 
`sam local invoke HelloWorldFunction --event event.json`

### Observed result
```
$ sam local invoke HelloWorldFunction --event event.json
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/configloader.py", line 149, in raw_config_parse
    cp.read([path])
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1065, in _read
    lineno)
configparser.DuplicateSectionError: While reading from '/Users/homeboy/.aws/credentials' [line 332]: section '156562137045' already exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.12.0', 'console_scripts', 'sam')()
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/samcli/cli/options.py", line 55, in callback
    state.profile = value
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/samcli/cli/context.py", line 69, in profile
    self._refresh_session()
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/samcli/cli/context.py", line 78, in _refresh_session
    profile_name=self._aws_profile)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/boto3/__init__.py", line 34, in setup_default_session
    DEFAULT_SESSION = Session(**kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/session.py", line 679, in get_component
    return self._components.get_component(name)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/session.py", line 902, in get_component
    self._components[name] = factory()
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/session.py", line 150, in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/session.py", line 233, in get_config_variable
    logical_name)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/configprovider.py", line 226, in get_config_variable
    return provider.provide()
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/configprovider.py", line 323, in provide
    value = provider.provide()
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/configprovider.py", line 382, in provide
    config = self._session.get_scoped_config()
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/session.py", line 324, in get_scoped_config
    profile_map = self._build_profile_map()
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/session.py", line 218, in _build_profile_map
    self._profile_map = self.full_config['profiles']
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/session.py", line 362, in full_config
    cred_file)
  File "/usr/local/Cellar/aws-sam-cli/0.12.0/libexec/lib/python3.7/site-packages/botocore/configloader.py", line 152, in raw_config_parse
    path=_unicode_path(path))
botocore.exceptions.ConfigParseError: Unable to parse config file: /Users/homeboy/.aws/credentials

```

### Expected result

working cli app

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OS X 10.11
2. `sam --version`: 0.12.0

`Add --debug flag to command you are running`

**Comment by TheSriram** [comment] 2019-04-18 20:29
I was not able to replicate this with a duplicate profile, can you provide structure of your credentials file?

**Comment by sriram-mv** [comment] 2020-02-10 19:13
This is used by aws cli as well, and read by boto too, and since this was not reproducible. I'm closing it out, please re-open if deemed necessary.

**Closed by sriram-mv** 2020-02-10 19:13 UTC
Labels: stage/needs-investigation, type/bug, type/ux

**Comment by sanjeevsharma020287** [comment] 2020-02-11 15:54
I agree to rojomisin. I was able to replicate the issue and It got fixed after deleting the duplicate entry in credentials file.
