### ISSUE TITLE
Tags with colons not treated correctly

### ISSUE THREAD

**Issue by gdietz** [awslabs/aws-sam-cli#1751] opened 2020-01-24 15:51 UTC
**Description:**

The `sam` CLI command does not treat tags with colons in them correctly.

**Steps to reproduce the issue:**
1. deploy a stack with `sam deploy --stack-name mystack --tags foo:bar=hello` 
2. Look at the tags on the stack and on any resource that supports them.

**Observed result:**
The tag key that gets attached to resources will be `bar` instead of `foo:bar`

**Expected result:**
The tag keys should match those specified in the CLI command.

**Notes**
The shorthand and JSON syntaxes for `--tags` also do not appear to be supported in `sam deploy --tags` compared to `cloudformation deploy --tags`

**Comment by jfuss** [comment] 2020-01-24 19:22
Duplicate of #1739 and there is already a PR open with a fix: #1727 

closing

**Closed by jfuss** 2020-01-24 19:22 UTC
