### ISSUE TITLE
Python: Don't fail on missing `requirements.txt`

### ISSUE THREAD

**Issue by milesgranger** [awslabs/aws-sam-cli#2115] opened 2020-07-20 07:46 UTC
### Describe your idea/feature/enhancement

If a particular function code uri doesn't contain a `requirements.txt` it should assume that there are no dependencies.

### Proposal

Don't raise an error like this:
```bash
Build Failed
Error: PythonPipBuilder:ResolveDependencies - Requirements file not found: /some/code/path/requirements.txt
```

Assume that a non-existing `requirements.txt` means there are simply no dependencies for this function. Otherwise one needs to have empty `requirements.txt` files laying around.

**Comment by sriram-mv** [comment] 2020-07-20 15:57
There is an expectation of a manifest when building from `aws-lambda-builders`, and an empty requirements.txt when using just included libraries is part of the contract, across languages.

**Comment by jfuss** [comment] 2020-07-20 21:49
duplicate of #784

Closing

**Closed by jfuss** 2020-07-20 21:49 UTC
Labels: area/build
