### ISSUE TITLE
Function returned an invalid response when error is not nil

### ISSUE THREAD

**Issue by dgoradia** [awslabs/aws-sam-cli#360] opened 2018-04-11 06:05 UTC
Using start-api, when there is an error returned in a proxy response, aws-sam-local returns a 502 with a body of `{ "message": "Internal server error" }`

Simple function:
```
func Handler(ctx context.Context, request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	err := errors.New("error bad request")

	return events.APIGatewayProxyResponse{
		StatusCode: 400,
		Body:       "{}",
	}, err
}

func main() {
	lambda.Start(Handler)
}
```

Response:
```
2018/04/10 22:59:34 Invoking bin/test_get (go1.x)
2018/04/10 22:59:34 Mounting /Users/dgoradia/go/src/api-lambda as /var/task:ro inside runtime container
2018/04/10 22:59:34 Connecting container 5e9045a0f6b861044049925114e5941ec14074b777bf690f04c49bce726995ca to network serverless_local
START RequestId: 8b17c6dd-bb7c-1f60-b643-7f42e2ddeeeb Version: $LATEST
END RequestId: 8b17c6dd-bb7c-1f60-b643-7f42e2ddeeeb
REPORT RequestId: 8b17c6dd-bb7c-1f60-b643-7f42e2ddeeeb	Duration: 1.36 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 5 MB
{
  "errorMessage": "error bad request",
  "errorType": "errorString"
}
2018/04/10 22:59:35 Function returned an invalid response (must include one of: body, headers or statusCode in the response object): unexpected end of JSON input
```

**Comment by jfuss** [comment] 2018-07-18 13:57
Ahh... this is the same as #522. There are some other conversations in that issue, so I am going to mark this as a duplicate of that one.

**Closed by jfuss** 2018-07-18 13:57 UTC
Labels: area/docker-lambda, area/local/start-api, stage/more-info-needed, type/duplicate
