### ISSUE TITLE
Official docker image for sam cli? 

### ISSUE THREAD

**Issue by red8888** [awslabs/aws-sam-cli#1973] opened 2020-05-10 17:37 UTC
AWS finally released an official image for the awscli but it doesn't look like it includes the sam cli? https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html

Is sam going to be added to it or will there be an official sam cli image too? An official image is even _more_ important for the sam cli than the aws cli.

This is important especially for CI/CD. The `--use-container` switch is important for building in a supported lambda environment. Running locally thats fine but all modern CI/CD systems build inside of containers already, this means for  `--use-container` to work DinD must be configured correctly which requires additional work/setup and requires more resources for the CI/CD system to run DinD

BUT if sam itself is already running in a container built from an image of a supported lambda environment `--use-container` isn't necessary.

Of course I could roll my own sam cli image, but this is something AWS should maintain. So I can reference that official image in my CI/CD build tool easily and not have to rebuild and keep it up to date manually

**Comment by jfuss** [comment] 2020-05-11 02:17
Duplicate of #804

Closing due to already having an issue for this ask.

**Closed by jfuss** 2020-05-11 02:17 UTC
