### ISSUE TITLE
Deploy a spring using Hibernate

### ISSUE THREAD

**Issue by NassimBounouas** [awslabs/aws-sam-cli#711] opened 2018-10-17 14:34 UTC
Hi,

**Description:**
I'm trying to deploy a spring application which is currently working on AWS Lambda. This application is using hibernate and to deploy it on SAM I'm using the same configuration (hsqldb) as used during the tests.

When I'm a calling a resource which isn't involving hibernate, everything is fine (for example : A method returning a hello world). When I'm calling a resource where hibernate is used (for example : List all entries of a table) I'm experiencing this type of error : 

<pre>
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:182)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:148)
        at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1984)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1914)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1892)
        at org.hibernate.loader.Loader.doQuery(Loader.java:937)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:340)
        at org.hibernate.loader.Loader.doList(Loader.java:2689)
        at org.hibernate.loader.Loader.doList(Loader.java:2672)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2506)
        at org.hibernate.loader.Loader.list(Loader.java:2501)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:504)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:395)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:221)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1506)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1538)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1506)
        ... 21 more
Caused by: java.sql.SQLSyntaxErrorException: unexpected token:  in statement [select candidate0_.`id` as id1_13_, candidate0_1_.email as email2_13_, candidate0_1_.firstName as firstNam3_13_, candidate0_1_.lastName as lastName4_13_, candidate0_1_.phoneNumber as phoneNum5_13_, candidate0_.birthDate as birthDat1_2_, candidate0_.civility as civility2_2_, candidate0_.comment as comment3_2_, candidate0_.creationDate as creation4_2_, candidate0_.currentProfile as currentP5_2_, candidate0_.mobility as mobility6_2_, candidate0_.nationality as national7_2_, candidate0_.`recruiter_id` as recruit15_2_, candidate0_.remuneration as remunera8_2_, candidate0_.sourceRecruitment as sourceRe9_2_, candidate0_. state as state10_2_, candidate0_.urlCV as urlCV11_2_, candidate0_.wantedProfile as wantedP12_2_, candidate0_.wantedRemuneration as wantedR13_2_ from `CANDIDATE` candidate0_ inner join `PERSON` candidate0_1_ on candidate0_.`id`=candidate0_1_.id]

</pre>

<pre>2018-10-17 13:04:12 [main] ERROR SqlExceptionHelper:131 - unexpected token:  in statement [select candidate0_.`id` as id1_13_, candidate0_1_.email as email2_13_, candidate0_1_.firstName as firstNam3_13_, candidate0_1_.lastName as lastName4_13_, candidate0_1_.phoneNumber as phoneNum5_13_, candidate0_.birthDate as birthDat1_2_, candidate0_.civility as civility2_2_, candidate0_.comment as comment3_2_, candidate0_.creationDate as creation4_2_, candidate0_.currentProfile as currentP5_2_, candidate0_.mobility as mobility6_2_, candidate0_.nationality as national7_2_, candidate0_.`recruiter_id` as recruit15_2_, candidate0_.remuneration as remunera8_2_, candidate0_.sourceRecruitment as sourceRe9_2_, candidate0_.state as state10_2_, candidate0_.urlCV as urlCV11_2_, candidate0_.wantedProfile as wantedP12_2_, candidate0_.wantedRemuneration as wantedR13_2_ from `CANDIDATE` candidate0_ inner join `PERSON` candidate0_1_ on candidate0_.`id`=candidate0_1_.id]</pre>

One of my remark was that the query is using backquote like in :
<pre>select candidate0_.`id`</pre>
and during the test phase the same field is used like that : 
<pre> select candidate0_."id"</pre>

However the same syntax is used during the database preparation (Create, Insert...) and the request is well executed.

I investigated for few hours without any improvement. The queries are working well outside sam and aren't hand written ; for example : 

<pre>Session session = sessionFactory.getCurrentSession();
CriteriaBuilder builder = session.getCriteriaBuilder();
CriteriaQuery<User> criteria = builder.createQuery(User.class);
Root<User> root =  criteria.from(User.class);
criteria.select(root).where(builder.equal(root.get("email"), email));
try {
    Optional<User> user = Optional.of(session.createQuery(criteria).getSingleResult());
    return user;
} catch (NoResultException  e) {
    logger.info("No user with email = "+email, e);
} catch (HibernateException e) {
    logger.error("Cannot execute query : getUserById", e);
}</pre>
 
Thank you for your help.

**Comment by jfuss** [comment] 2018-10-24 14:32
This isn't related to SAM CLI directly. The code is being mounted and run. The error you are seeing is caused by the hibernate library.

Closing this since this is an error with hibernate not SAM CLI.

**Closed by jfuss** 2018-10-24 14:32 UTC
